//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.Room;
using HengDa.LiZongMing.REAMS.Room.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.Room
{

    /// <summary>
    /// 站房环境状态 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.RoomRunStatus.Default*/)]
    public partial class RoomRunStatusAppService : REAMSAppServiceBase<RoomRunStatus, RoomRunStatusDto, Guid, RoomRunStatusPagedRequest, RoomRunStatusDto, RoomRunStatusDto>, IRoomRunStatusAppService
    {

        #region 构造方法

        //private readonly RoomRunStatusManager _roomRunStatusManager;

        public RoomRunStatusAppService(
            IRoomRunStatusRepository repository  //mongodb必须用这个             IRepository<RoomRunStatus, Guid> repository
            //RoomRunStatusManager roomRunStatusManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.RoomRunStatus.Query;
            //GetListPolicyName = REAMSPermissions.RoomRunStatus.Query;
            //CreatePolicyName = REAMSPermissions.RoomRunStatus.Create;
            //UpdatePolicyName = REAMSPermissions.RoomRunStatus.Edit;
            //DeletePolicyName = REAMSPermissions.RoomRunStatus.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.RoomRunStatus.Query)]
        public override Task<RoomRunStatusDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.RoomRunStatus.Query)]
        public override Task<PagedResultDto<RoomRunStatusDto>> GetListAsync(RoomRunStatusPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.RoomRunStatus.Create)]
        public async Task<RoomRunStatusDto> GetOrNew(Nullable<Guid> id)
        {
            RoomRunStatusDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new RoomRunStatusDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.RoomRunStatus.Create)]
        public override async Task<RoomRunStatusDto> CreateAsync(RoomRunStatusDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var roomRunStatus = MapToEntity(input);
            //return MapToGetOutputDto(roomRunStatus);
        }

        [Authorize(REAMSPermissions.RoomRunStatus.Edit)]
        public override async Task<RoomRunStatusDto> UpdateAsync(Guid id, RoomRunStatusDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var roomRunStatus = await _roomRunStatusManager.GetRoomRunStatusByIdAsync(input.Id);
            //MapToEntity(input, roomRunStatus);
            //CheckErrors(await _roomRunStatusManager.UpdateAsync(roomRunStatus));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _roomRunStatusManager.SetRoles(roomRunStatus, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.RoomRunStatus.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var roomRunStatus = await _roomRunStatusManager.GetRoomRunStatusByIdAsync(id);
            //await _roomRunStatusManager.DeleteAsync(roomRunStatus);
        }

        protected override async Task<RoomRunStatus> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var roomRunStatus = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (roomRunStatus == null)
            //{
            //    throw new EntityNotFoundException(typeof(RoomRunStatus), id);
            //}
            //return roomRunStatus;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="RoomRunStatus"/> 时转换为 <see cref="RoomRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual RoomRunStatusDto MapToGetOutputDto(RoomRunStatus entity)
        {
            //return ObjectMapper.Map<RoomRunStatus, RoomRunStatusDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="RoomRunStatus"/> 时转换为 <see cref="RoomRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<RoomRunStatusDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override RoomRunStatus MapToEntity(RoomRunStatusDto createInput)
        {
            return base.MapToEntity(createInput);
            //var roomRunStatus = ObjectMapper.Map<RoomRunStatus>(createInput);
            //roomRunStatus.SetNormalizedNames();
            //return roomRunStatus;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(RoomRunStatusDto updateInput, RoomRunStatus roomRunStatus)
        {
            base.MapToEntity(updateInput, roomRunStatus);
            //ObjectMapper.Map(updateInput, roomRunStatus);
            //roomRunStatus.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<RoomRunStatus>> CreateFilteredQueryAsync(RoomRunStatusPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<RoomRunStatus> ApplySorting(IQueryable<RoomRunStatus> query, RoomRunStatusPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}