//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.DLL;
using HengDa.LiZongMing.REAMS.DLL.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.DLL
{

    /// <summary>
    /// DLL检测记录 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.DllRecord.Default*/)]
    public partial class DllRecordAppService : REAMSAppServiceBase<DllRecord, DllRecordDto, Guid, DllRecordPagedRequest, DllRecordDto, DllRecordDto>, IDllRecordAppService
    {

        #region 构造方法

        //private readonly DllRecordManager _dllRecordManager;

        public DllRecordAppService(
            IDllRecordRepository repository  //mongodb必须用这个             IRepository<DllRecord, Guid> repository
            //DllRecordManager dllRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.DllRecord.Query;
            //GetListPolicyName = REAMSPermissions.DllRecord.Query;
            //CreatePolicyName = REAMSPermissions.DllRecord.Create;
            //UpdatePolicyName = REAMSPermissions.DllRecord.Edit;
            //DeletePolicyName = REAMSPermissions.DllRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.DllRecord.Query)]
        public override Task<DllRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.DllRecord.Query)]
        public override Task<PagedResultDto<DllRecordDto>> GetListAsync(DllRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.DllRecord.Create)]
        public async Task<DllRecordDto> GetOrNew(Nullable<Guid> id)
        {
            DllRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new DllRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.DllRecord.Create)]
        public override async Task<DllRecordDto> CreateAsync(DllRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var dllRecord = MapToEntity(input);
            //return MapToGetOutputDto(dllRecord);
        }

        [Authorize(REAMSPermissions.DllRecord.Edit)]
        public override async Task<DllRecordDto> UpdateAsync(Guid id, DllRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var dllRecord = await _dllRecordManager.GetDllRecordByIdAsync(input.Id);
            //MapToEntity(input, dllRecord);
            //CheckErrors(await _dllRecordManager.UpdateAsync(dllRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _dllRecordManager.SetRoles(dllRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.DllRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var dllRecord = await _dllRecordManager.GetDllRecordByIdAsync(id);
            //await _dllRecordManager.DeleteAsync(dllRecord);
        }

        protected override async Task<DllRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var dllRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (dllRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(DllRecord), id);
            //}
            //return dllRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="DllRecord"/> 时转换为 <see cref="DllRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual DllRecordDto MapToGetOutputDto(DllRecord entity)
        {
            //return ObjectMapper.Map<DllRecord, DllRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="DllRecord"/> 时转换为 <see cref="DllRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<DllRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override DllRecord MapToEntity(DllRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var dllRecord = ObjectMapper.Map<DllRecord>(createInput);
            //dllRecord.SetNormalizedNames();
            //return dllRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(DllRecordDto updateInput, DllRecord dllRecord)
        {
            base.MapToEntity(updateInput, dllRecord);
            //ObjectMapper.Map(updateInput, dllRecord);
            //dllRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<DllRecord>> CreateFilteredQueryAsync(DllRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.rawData.Contains(input.Keyword)
                        )
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(!input.BatchNumber.IsNullOrWhiteSpace(), x => x.BatchNumber == input.BatchNumber)
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<DllRecord> ApplySorting(IQueryable<DllRecord> query, DllRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}