//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.DLL;
using HengDa.LiZongMing.REAMS.DLL.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.DLL
{

    /// <summary>
    /// DLL设备参数信息 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.DllSetting.Default*/)]
    public partial class DllSettingAppService : REAMSAppServiceBase<DllSetting, DllSettingDto, Guid, DllSettingPagedRequest, DllSettingDto, DllSettingDto>, IDllSettingAppService
    {

        #region 构造方法

        //private readonly DllSettingManager _dllSettingManager;

        public DllSettingAppService(
            IDllSettingRepository repository  //mongodb必须用这个             IRepository<DllSetting, Guid> repository
            //DllSettingManager dllSettingManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.DllSetting.Query;
            //GetListPolicyName = REAMSPermissions.DllSetting.Query;
            //CreatePolicyName = REAMSPermissions.DllSetting.Create;
            //UpdatePolicyName = REAMSPermissions.DllSetting.Edit;
            //DeletePolicyName = REAMSPermissions.DllSetting.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.DllSetting.Query)]
        public override Task<DllSettingDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.DllSetting.Query)]
        public override Task<PagedResultDto<DllSettingDto>> GetListAsync(DllSettingPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.DllSetting.Create)]
        public async Task<DllSettingDto> GetOrNew(Nullable<Guid> id)
        {
            DllSettingDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new DllSettingDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.DllSetting.Create)]
        public override async Task<DllSettingDto> CreateAsync(DllSettingDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var dllSetting = MapToEntity(input);
            //return MapToGetOutputDto(dllSetting);
        }

        [Authorize(REAMSPermissions.DllSetting.Edit)]
        public override async Task<DllSettingDto> UpdateAsync(Guid id, DllSettingDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var dllSetting = await _dllSettingManager.GetDllSettingByIdAsync(input.Id);
            //MapToEntity(input, dllSetting);
            //CheckErrors(await _dllSettingManager.UpdateAsync(dllSetting));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _dllSettingManager.SetRoles(dllSetting, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.DllSetting.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var dllSetting = await _dllSettingManager.GetDllSettingByIdAsync(id);
            //await _dllSettingManager.DeleteAsync(dllSetting);
        }

        protected override async Task<DllSetting> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var dllSetting = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (dllSetting == null)
            //{
            //    throw new EntityNotFoundException(typeof(DllSetting), id);
            //}
            //return dllSetting;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="DllSetting"/> 时转换为 <see cref="DllSettingDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual DllSettingDto MapToGetOutputDto(DllSetting entity)
        {
            //return ObjectMapper.Map<DllSetting, DllSettingDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="DllSetting"/> 时转换为 <see cref="DllSettingDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<DllSettingDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override DllSetting MapToEntity(DllSettingDto createInput)
        {
            return base.MapToEntity(createInput);
            //var dllSetting = ObjectMapper.Map<DllSetting>(createInput);
            //dllSetting.SetNormalizedNames();
            //return dllSetting;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(DllSettingDto updateInput, DllSetting dllSetting)
        {
            base.MapToEntity(updateInput, dllSetting);
            //ObjectMapper.Map(updateInput, dllSetting);
            //dllSetting.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<DllSetting>> CreateFilteredQueryAsync(DllSettingPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(!input.BatchNumber.IsNullOrWhiteSpace(), x => x.BatchNumber == input.BatchNumber)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<DllSetting> ApplySorting(IQueryable<DllSetting> query, DllSettingPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}