//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------


using AutoMapper;

using HengDa.LiZongMing.REAMS.RNS;
using HengDa.LiZongMing.REAMS.RNS.Dtos;
using HengDa.LiZongMing.REAMS.Room;
using HengDa.LiZongMing.REAMS.Room.Dtos;
using HengDa.LiZongMing.REAMS.NBS;
using HengDa.LiZongMing.REAMS.NBS.Dtos;
using HengDa.LiZongMing.REAMS.NaI;
using HengDa.LiZongMing.REAMS.NaI.Dtos;
using HengDa.LiZongMing.REAMS.HVE;
using HengDa.LiZongMing.REAMS.HVE.Dtos;
using HengDa.LiZongMing.REAMS.ZJC;
using HengDa.LiZongMing.REAMS.ZJC.Dtos;
using HengDa.LiZongMing.REAMS.Devices;
using HengDa.LiZongMing.REAMS.Devices.Dtos;
using HengDa.LiZongMing.REAMS.DLL;
using HengDa.LiZongMing.REAMS.DLL.Dtos;
using HengDa.LiZongMing.REAMS.Atm;
using HengDa.LiZongMing.REAMS.Atm.Dtos;
using HengDa.LiZongMing.REAMS.ZCQ;
using HengDa.LiZongMing.REAMS.ZCQ.Dtos;
using HengDa.LiZongMing.REAMS.Crm;
using HengDa.LiZongMing.REAMS.Crm.Dtos;
namespace HengDa.LiZongMing.REAMS
{
    public class REAMSApplicationAutoMapperProfile : Profile
    {
        public REAMSApplicationAutoMapperProfile()
        {
            /* You can configure your AutoMapper mapping configuration here.
             * Alternatively, you can split your mapping configurations
             * into multiple profile classes for a better organization. */

            #region 不保留  CreateMap


            CreateMap<RnsRunStatus, RnsRunStatusDto>();
            CreateMap<RnsRunStatusDto, RnsRunStatus>();

            CreateMap<RoomRunStatus, RoomRunStatusDto>();
            CreateMap<RoomRunStatusDto, RoomRunStatus>();

            CreateMap<NbsRunStatus, NbsRunStatusDto>();
            CreateMap<NbsRunStatusDto, NbsRunStatus>();

            CreateMap<NbsRecord, NbsRecordDto>();
            CreateMap<NbsRecordDto, NbsRecord>();

            CreateMap<NaiRecord, NaiRecordDto>();
            CreateMap<NaiRecordDto, NaiRecord>();

            CreateMap<HveRunStatus, HveRunStatusDto>();
            CreateMap<HveRunStatusDto, HveRunStatus>();

            CreateMap<HveRecord, HveRecordDto>();
            CreateMap<HveRecordDto, HveRecord>();

            CreateMap<HveExtRecord, HveExtRecordDto>();
            CreateMap<HveExtRecordDto, HveExtRecord>();

            CreateMap<ZjcRainRecord, ZjcRainRecordDto>();
            CreateMap<ZjcRainRecordDto, ZjcRainRecord>();

            CreateMap<ZjcRecord, ZjcRecordDto>();
            CreateMap<ZjcRecordDto, ZjcRecord>();

            CreateMap<ZjcRunStatus, ZjcRunStatusDto>();
            CreateMap<ZjcRunStatusDto, ZjcRunStatus>();

            CreateMap<IotDeviceLog, IotDeviceLogDto>();
            CreateMap<IotDeviceLogDto, IotDeviceLog>();

            CreateMap<IotDeviceAlarm, IotDeviceAlarmDto>();
            CreateMap<IotDeviceAlarmDto, IotDeviceAlarm>();

            CreateMap<DllRecord, DllRecordDto>();
            CreateMap<DllRecordDto, DllRecord>();

            CreateMap<DllSetting, DllSettingDto>();
            CreateMap<DllSettingDto, DllSetting>();

            CreateMap<AtmosphereRecord, AtmosphereRecordDto>();
            CreateMap<AtmosphereRecordDto, AtmosphereRecord>();

            CreateMap<ZcqRunStatus, ZcqRunStatusDto>();
            CreateMap<ZcqRunStatusDto, ZcqRunStatus>();

            CreateMap<ZcqRecord, ZcqRecordDto>();
            CreateMap<ZcqRecordDto, ZcqRecord>();

            CreateMap<Device, DeviceDto>();
            CreateMap<DeviceDto, Device>();

            CreateMap<DeviceRoom, DeviceRoomDto>();
            CreateMap<DeviceRoomDto, DeviceRoom>();

            CreateMap<Customer, CustomerDto>();
            CreateMap<CustomerDto, Customer>();

            CreateMap<CustomerService, CustomerServiceDto>();
            CreateMap<CustomerServiceDto, CustomerService>();


            #endregion

            #region 保留  手动添加mapping

            #endregion        }



    }
}

