//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.HVE;
using HengDa.LiZongMing.REAMS.HVE.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.HVE
{

    /// <summary>
    /// 高压电离记录 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.HveExtRecord.Default*/)]
    public partial class HveExtRecordAppService : REAMSAppServiceBase<HveExtRecord, HveExtRecordDto, Guid, HveExtRecordPagedRequest, HveExtRecordDto, HveExtRecordDto>, IHveExtRecordAppService
    {

        #region 构造方法

        //private readonly HveExtRecordManager _hveExtRecordManager;

        public HveExtRecordAppService(
            IHveExtRecordRepository repository  //mongodb必须用这个             IRepository<HveExtRecord, Guid> repository
            //HveExtRecordManager hveExtRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.HveExtRecord.Query;
            //GetListPolicyName = REAMSPermissions.HveExtRecord.Query;
            //CreatePolicyName = REAMSPermissions.HveExtRecord.Create;
            //UpdatePolicyName = REAMSPermissions.HveExtRecord.Edit;
            //DeletePolicyName = REAMSPermissions.HveExtRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.HveExtRecord.Query)]
        public override Task<HveExtRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.HveExtRecord.Query)]
        public override Task<PagedResultDto<HveExtRecordDto>> GetListAsync(HveExtRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.HveExtRecord.Create)]
        public async Task<HveExtRecordDto> GetOrNew(Nullable<Guid> id)
        {
            HveExtRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new HveExtRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.HveExtRecord.Create)]
        public override async Task<HveExtRecordDto> CreateAsync(HveExtRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var hveExtRecord = MapToEntity(input);
            //return MapToGetOutputDto(hveExtRecord);
        }

        [Authorize(REAMSPermissions.HveExtRecord.Edit)]
        public override async Task<HveExtRecordDto> UpdateAsync(Guid id, HveExtRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var hveExtRecord = await _hveExtRecordManager.GetHveExtRecordByIdAsync(input.Id);
            //MapToEntity(input, hveExtRecord);
            //CheckErrors(await _hveExtRecordManager.UpdateAsync(hveExtRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _hveExtRecordManager.SetRoles(hveExtRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.HveExtRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var hveExtRecord = await _hveExtRecordManager.GetHveExtRecordByIdAsync(id);
            //await _hveExtRecordManager.DeleteAsync(hveExtRecord);
        }

        protected override async Task<HveExtRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var hveExtRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (hveExtRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(HveExtRecord), id);
            //}
            //return hveExtRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="HveExtRecord"/> 时转换为 <see cref="HveExtRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual HveExtRecordDto MapToGetOutputDto(HveExtRecord entity)
        {
            //return ObjectMapper.Map<HveExtRecord, HveExtRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="HveExtRecord"/> 时转换为 <see cref="HveExtRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<HveExtRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override HveExtRecord MapToEntity(HveExtRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var hveExtRecord = ObjectMapper.Map<HveExtRecord>(createInput);
            //hveExtRecord.SetNormalizedNames();
            //return hveExtRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(HveExtRecordDto updateInput, HveExtRecord hveExtRecord)
        {
            base.MapToEntity(updateInput, hveExtRecord);
            //ObjectMapper.Map(updateInput, hveExtRecord);
            //hveExtRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<HveExtRecord>> CreateFilteredQueryAsync(HveExtRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<HveExtRecord> ApplySorting(IQueryable<HveExtRecord> query, HveExtRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}