//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.HVE;
using HengDa.LiZongMing.REAMS.HVE.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.HVE
{

    /// <summary>
    /// 高压电离伽马记录 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.HveRecord.Default*/)]
    public partial class HveRecordAppService : REAMSAppServiceBase<HveRecord, HveRecordDto, Guid, HveRecordPagedRequest, HveRecordDto, HveRecordDto>, IHveRecordAppService
    {

        #region 构造方法

        //private readonly HveRecordManager _hveRecordManager;

        public HveRecordAppService(
            IHveRecordRepository repository  //mongodb必须用这个             IRepository<HveRecord, Guid> repository
            //HveRecordManager hveRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.HveRecord.Query;
            //GetListPolicyName = REAMSPermissions.HveRecord.Query;
            //CreatePolicyName = REAMSPermissions.HveRecord.Create;
            //UpdatePolicyName = REAMSPermissions.HveRecord.Edit;
            //DeletePolicyName = REAMSPermissions.HveRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.HveRecord.Query)]
        public override Task<HveRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.HveRecord.Query)]
        public override Task<PagedResultDto<HveRecordDto>> GetListAsync(HveRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.HveRecord.Create)]
        public async Task<HveRecordDto> GetOrNew(Nullable<Guid> id)
        {
            HveRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new HveRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.HveRecord.Create)]
        public override async Task<HveRecordDto> CreateAsync(HveRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var hveRecord = MapToEntity(input);
            //return MapToGetOutputDto(hveRecord);
        }

        [Authorize(REAMSPermissions.HveRecord.Edit)]
        public override async Task<HveRecordDto> UpdateAsync(Guid id, HveRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var hveRecord = await _hveRecordManager.GetHveRecordByIdAsync(input.Id);
            //MapToEntity(input, hveRecord);
            //CheckErrors(await _hveRecordManager.UpdateAsync(hveRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _hveRecordManager.SetRoles(hveRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.HveRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var hveRecord = await _hveRecordManager.GetHveRecordByIdAsync(id);
            //await _hveRecordManager.DeleteAsync(hveRecord);
        }

        protected override async Task<HveRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var hveRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (hveRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(HveRecord), id);
            //}
            //return hveRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="HveRecord"/> 时转换为 <see cref="HveRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual HveRecordDto MapToGetOutputDto(HveRecord entity)
        {
            //return ObjectMapper.Map<HveRecord, HveRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="HveRecord"/> 时转换为 <see cref="HveRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<HveRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override HveRecord MapToEntity(HveRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var hveRecord = ObjectMapper.Map<HveRecord>(createInput);
            //hveRecord.SetNormalizedNames();
            //return hveRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(HveRecordDto updateInput, HveRecord hveRecord)
        {
            base.MapToEntity(updateInput, hveRecord);
            //ObjectMapper.Map(updateInput, hveRecord);
            //hveRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<HveRecord>> CreateFilteredQueryAsync(HveRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<HveRecord> ApplySorting(IQueryable<HveRecord> query, HveRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}