//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.HVE;
using HengDa.LiZongMing.REAMS.HVE.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.HVE
{

    /// <summary>
    /// 高压电离状态 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.HveRunStatus.Default*/)]
    public partial class HveRunStatusAppService : REAMSAppServiceBase<HveRunStatus, HveRunStatusDto, Guid, HveRunStatusPagedRequest, HveRunStatusDto, HveRunStatusDto>, IHveRunStatusAppService
    {

        #region 构造方法

        //private readonly HveRunStatusManager _hveRunStatusManager;

        public HveRunStatusAppService(
            IHveRunStatusRepository repository  //mongodb必须用这个             IRepository<HveRunStatus, Guid> repository
            //HveRunStatusManager hveRunStatusManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.HveRunStatus.Query;
            //GetListPolicyName = REAMSPermissions.HveRunStatus.Query;
            //CreatePolicyName = REAMSPermissions.HveRunStatus.Create;
            //UpdatePolicyName = REAMSPermissions.HveRunStatus.Edit;
            //DeletePolicyName = REAMSPermissions.HveRunStatus.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.HveRunStatus.Query)]
        public override Task<HveRunStatusDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.HveRunStatus.Query)]
        public override Task<PagedResultDto<HveRunStatusDto>> GetListAsync(HveRunStatusPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.HveRunStatus.Create)]
        public async Task<HveRunStatusDto> GetOrNew(Nullable<Guid> id)
        {
            HveRunStatusDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new HveRunStatusDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.HveRunStatus.Create)]
        public override async Task<HveRunStatusDto> CreateAsync(HveRunStatusDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var hveRunStatus = MapToEntity(input);
            //return MapToGetOutputDto(hveRunStatus);
        }

        [Authorize(REAMSPermissions.HveRunStatus.Edit)]
        public override async Task<HveRunStatusDto> UpdateAsync(Guid id, HveRunStatusDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var hveRunStatus = await _hveRunStatusManager.GetHveRunStatusByIdAsync(input.Id);
            //MapToEntity(input, hveRunStatus);
            //CheckErrors(await _hveRunStatusManager.UpdateAsync(hveRunStatus));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _hveRunStatusManager.SetRoles(hveRunStatus, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.HveRunStatus.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var hveRunStatus = await _hveRunStatusManager.GetHveRunStatusByIdAsync(id);
            //await _hveRunStatusManager.DeleteAsync(hveRunStatus);
        }

        protected override async Task<HveRunStatus> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var hveRunStatus = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (hveRunStatus == null)
            //{
            //    throw new EntityNotFoundException(typeof(HveRunStatus), id);
            //}
            //return hveRunStatus;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="HveRunStatus"/> 时转换为 <see cref="HveRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual HveRunStatusDto MapToGetOutputDto(HveRunStatus entity)
        {
            //return ObjectMapper.Map<HveRunStatus, HveRunStatusDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="HveRunStatus"/> 时转换为 <see cref="HveRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<HveRunStatusDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override HveRunStatus MapToEntity(HveRunStatusDto createInput)
        {
            return base.MapToEntity(createInput);
            //var hveRunStatus = ObjectMapper.Map<HveRunStatus>(createInput);
            //hveRunStatus.SetNormalizedNames();
            //return hveRunStatus;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(HveRunStatusDto updateInput, HveRunStatus hveRunStatus)
        {
            base.MapToEntity(updateInput, hveRunStatus);
            //ObjectMapper.Map(updateInput, hveRunStatus);
            //hveRunStatus.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<HveRunStatus>> CreateFilteredQueryAsync(HveRunStatusPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<HveRunStatus> ApplySorting(IQueryable<HveRunStatus> query, HveRunStatusPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}