//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Domain.Repositories.MongoDB;
using Volo.Abp.MongoDB;

using HengDa.LiZongMing.REAMS.MongoDB;


namespace HengDa.LiZongMing.REAMS.HVE
{

    public class HveRunStatusRepository : MongoDbRepository<IREAMSMongoDbContext, HveRunStatus, Guid>, IHveRunStatusRepository
    {
        public HveRunStatusRepository(IMongoDbContextProvider<IREAMSMongoDbContext> dbContextProvider) : base(dbContextProvider)
        {
        }

        #region 不保留  手动添加方法

        #endregion

    }
}