//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.HVE.Dtos
{

    /// <summary>
    /// 高压电离记录 Dto
    /// </summary>
    //[AutoMapFrom(typeof(HveExtRecord))]
public partial class HveExtRecordDto : EntityDto<Guid>
    {
        #region 构造方法
        public HveExtRecordDto()
        {
        }
        #endregion


        #region 基本属性

        // ///<summary>
        // /// Id
        // ///</summary>
        // [Display(Name = "Id", Order = 1)]
        // public virtual Guid Id { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 2)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 3)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 集成温度
        ///</summary>
        [Display(Name = "集成温度", Order = 4)]
        public virtual decimal IntegratorTemperature { get; set; }


        ///<summary>
        /// 静电计湿度
        ///</summary>
        [Display(Name = "静电计湿度", Order = 5)]
        public virtual decimal ElectrometerHumidity { get; set; }


        ///<summary>
        /// 电池电流
        ///</summary>
        [Display(Name = "电池电流", Order = 6)]
        public virtual decimal BatteryCurrent { get; set; }


        ///<summary>
        /// 电池温度
        ///</summary>
        [Display(Name = "电池温度", Order = 7)]
        public virtual decimal BatteryTemperature { get; set; }


        ///<summary>
        /// 剩余电池容量
        ///</summary>
        [Display(Name = "剩余电池容量", Order = 8)]
        public virtual decimal RemainingBatteryCapacity { get; set; }


        ///<summary>
        /// 完全充电电池容量
        ///</summary>
        [Display(Name = "完全充电电池容量", Order = 9)]
        public virtual decimal FullChargeBatteryCapacity { get; set; }


        ///<summary>
        /// 电池容量百分比
        ///</summary>
        [Display(Name = "电池容量百分比", Order = 10)]
        public virtual decimal PercentBatteryCapacity { get; set; }


        ///<summary>
        /// 正常运行时间
        ///</summary>
        [Display(Name = "正常运行时间", Order = 11)]
        public virtual decimal Uptime { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 12)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}