//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS.Localization;
using Volo.Abp.Authorization.Permissions;
using Volo.Abp.Localization;

namespace HengDa.LiZongMing.REAMS.Authorization
{
    public class REAMSPermissionDefinitionProvider : PermissionDefinitionProvider
    {
        public override void Define(IPermissionDefinitionContext context)
        {
            //var moduleGroup = context.AddGroup(REAMSPermissions.GroupName, L("Permission: IotManage"));
            var ptGroup = context.AddGroup(REAMSPermissions.GroupName, L("Permission: REAMS"));

            var RnsRunStatus = ptGroup.AddPermission(REAMSPermissions.RnsRunStatus.Default, L("Permission:RnsRunStatus"));
            RnsRunStatus.AddChild(REAMSPermissions.RnsRunStatus.Query, L("Permission:Query"));
            RnsRunStatus.AddChild(REAMSPermissions.RnsRunStatus.Create, L("Permission:Create"));
            RnsRunStatus.AddChild(REAMSPermissions.RnsRunStatus.Edit, L("Permission:Edit"));
            RnsRunStatus.AddChild(REAMSPermissions.RnsRunStatus.Delete, L("Permission:Delete"));
            //RnsRunStatus.AddChild(REAMSPermissions.RnsRunStatus.BatchDelete, L("Permission:BatchDelete"));
            //RnsRunStatus.AddChild(REAMSPermissions.RnsRunStatus.ExportExcel, L("Permission:ExportExcel"));

            var RoomRunStatus = ptGroup.AddPermission(REAMSPermissions.RoomRunStatus.Default, L("Permission:RoomRunStatus"));
            RoomRunStatus.AddChild(REAMSPermissions.RoomRunStatus.Query, L("Permission:Query"));
            RoomRunStatus.AddChild(REAMSPermissions.RoomRunStatus.Create, L("Permission:Create"));
            RoomRunStatus.AddChild(REAMSPermissions.RoomRunStatus.Edit, L("Permission:Edit"));
            RoomRunStatus.AddChild(REAMSPermissions.RoomRunStatus.Delete, L("Permission:Delete"));
            //RoomRunStatus.AddChild(REAMSPermissions.RoomRunStatus.BatchDelete, L("Permission:BatchDelete"));
            //RoomRunStatus.AddChild(REAMSPermissions.RoomRunStatus.ExportExcel, L("Permission:ExportExcel"));

            var NbsRunStatus = ptGroup.AddPermission(REAMSPermissions.NbsRunStatus.Default, L("Permission:NbsRunStatus"));
            NbsRunStatus.AddChild(REAMSPermissions.NbsRunStatus.Query, L("Permission:Query"));
            NbsRunStatus.AddChild(REAMSPermissions.NbsRunStatus.Create, L("Permission:Create"));
            NbsRunStatus.AddChild(REAMSPermissions.NbsRunStatus.Edit, L("Permission:Edit"));
            NbsRunStatus.AddChild(REAMSPermissions.NbsRunStatus.Delete, L("Permission:Delete"));
            //NbsRunStatus.AddChild(REAMSPermissions.NbsRunStatus.BatchDelete, L("Permission:BatchDelete"));
            //NbsRunStatus.AddChild(REAMSPermissions.NbsRunStatus.ExportExcel, L("Permission:ExportExcel"));

            var NbsRecord = ptGroup.AddPermission(REAMSPermissions.NbsRecord.Default, L("Permission:NbsRecord"));
            NbsRecord.AddChild(REAMSPermissions.NbsRecord.Query, L("Permission:Query"));
            NbsRecord.AddChild(REAMSPermissions.NbsRecord.Create, L("Permission:Create"));
            NbsRecord.AddChild(REAMSPermissions.NbsRecord.Edit, L("Permission:Edit"));
            NbsRecord.AddChild(REAMSPermissions.NbsRecord.Delete, L("Permission:Delete"));
            //NbsRecord.AddChild(REAMSPermissions.NbsRecord.BatchDelete, L("Permission:BatchDelete"));
            //NbsRecord.AddChild(REAMSPermissions.NbsRecord.ExportExcel, L("Permission:ExportExcel"));

            var NaiRecord = ptGroup.AddPermission(REAMSPermissions.NaiRecord.Default, L("Permission:NaiRecord"));
            NaiRecord.AddChild(REAMSPermissions.NaiRecord.Query, L("Permission:Query"));
            NaiRecord.AddChild(REAMSPermissions.NaiRecord.Create, L("Permission:Create"));
            NaiRecord.AddChild(REAMSPermissions.NaiRecord.Edit, L("Permission:Edit"));
            NaiRecord.AddChild(REAMSPermissions.NaiRecord.Delete, L("Permission:Delete"));
            //NaiRecord.AddChild(REAMSPermissions.NaiRecord.BatchDelete, L("Permission:BatchDelete"));
            //NaiRecord.AddChild(REAMSPermissions.NaiRecord.ExportExcel, L("Permission:ExportExcel"));

            var HveRunStatus = ptGroup.AddPermission(REAMSPermissions.HveRunStatus.Default, L("Permission:HveRunStatus"));
            HveRunStatus.AddChild(REAMSPermissions.HveRunStatus.Query, L("Permission:Query"));
            HveRunStatus.AddChild(REAMSPermissions.HveRunStatus.Create, L("Permission:Create"));
            HveRunStatus.AddChild(REAMSPermissions.HveRunStatus.Edit, L("Permission:Edit"));
            HveRunStatus.AddChild(REAMSPermissions.HveRunStatus.Delete, L("Permission:Delete"));
            //HveRunStatus.AddChild(REAMSPermissions.HveRunStatus.BatchDelete, L("Permission:BatchDelete"));
            //HveRunStatus.AddChild(REAMSPermissions.HveRunStatus.ExportExcel, L("Permission:ExportExcel"));

            var HveRecord = ptGroup.AddPermission(REAMSPermissions.HveRecord.Default, L("Permission:HveRecord"));
            HveRecord.AddChild(REAMSPermissions.HveRecord.Query, L("Permission:Query"));
            HveRecord.AddChild(REAMSPermissions.HveRecord.Create, L("Permission:Create"));
            HveRecord.AddChild(REAMSPermissions.HveRecord.Edit, L("Permission:Edit"));
            HveRecord.AddChild(REAMSPermissions.HveRecord.Delete, L("Permission:Delete"));
            //HveRecord.AddChild(REAMSPermissions.HveRecord.BatchDelete, L("Permission:BatchDelete"));
            //HveRecord.AddChild(REAMSPermissions.HveRecord.ExportExcel, L("Permission:ExportExcel"));

            var HveExtRecord = ptGroup.AddPermission(REAMSPermissions.HveExtRecord.Default, L("Permission:HveExtRecord"));
            HveExtRecord.AddChild(REAMSPermissions.HveExtRecord.Query, L("Permission:Query"));
            HveExtRecord.AddChild(REAMSPermissions.HveExtRecord.Create, L("Permission:Create"));
            HveExtRecord.AddChild(REAMSPermissions.HveExtRecord.Edit, L("Permission:Edit"));
            HveExtRecord.AddChild(REAMSPermissions.HveExtRecord.Delete, L("Permission:Delete"));
            //HveExtRecord.AddChild(REAMSPermissions.HveExtRecord.BatchDelete, L("Permission:BatchDelete"));
            //HveExtRecord.AddChild(REAMSPermissions.HveExtRecord.ExportExcel, L("Permission:ExportExcel"));

            var ZjcRainRecord = ptGroup.AddPermission(REAMSPermissions.ZjcRainRecord.Default, L("Permission:ZjcRainRecord"));
            ZjcRainRecord.AddChild(REAMSPermissions.ZjcRainRecord.Query, L("Permission:Query"));
            ZjcRainRecord.AddChild(REAMSPermissions.ZjcRainRecord.Create, L("Permission:Create"));
            ZjcRainRecord.AddChild(REAMSPermissions.ZjcRainRecord.Edit, L("Permission:Edit"));
            ZjcRainRecord.AddChild(REAMSPermissions.ZjcRainRecord.Delete, L("Permission:Delete"));
            //ZjcRainRecord.AddChild(REAMSPermissions.ZjcRainRecord.BatchDelete, L("Permission:BatchDelete"));
            //ZjcRainRecord.AddChild(REAMSPermissions.ZjcRainRecord.ExportExcel, L("Permission:ExportExcel"));

            var ZjcRecord = ptGroup.AddPermission(REAMSPermissions.ZjcRecord.Default, L("Permission:ZjcRecord"));
            ZjcRecord.AddChild(REAMSPermissions.ZjcRecord.Query, L("Permission:Query"));
            ZjcRecord.AddChild(REAMSPermissions.ZjcRecord.Create, L("Permission:Create"));
            ZjcRecord.AddChild(REAMSPermissions.ZjcRecord.Edit, L("Permission:Edit"));
            ZjcRecord.AddChild(REAMSPermissions.ZjcRecord.Delete, L("Permission:Delete"));
            //ZjcRecord.AddChild(REAMSPermissions.ZjcRecord.BatchDelete, L("Permission:BatchDelete"));
            //ZjcRecord.AddChild(REAMSPermissions.ZjcRecord.ExportExcel, L("Permission:ExportExcel"));

            var ZjcRunStatus = ptGroup.AddPermission(REAMSPermissions.ZjcRunStatus.Default, L("Permission:ZjcRunStatus"));
            ZjcRunStatus.AddChild(REAMSPermissions.ZjcRunStatus.Query, L("Permission:Query"));
            ZjcRunStatus.AddChild(REAMSPermissions.ZjcRunStatus.Create, L("Permission:Create"));
            ZjcRunStatus.AddChild(REAMSPermissions.ZjcRunStatus.Edit, L("Permission:Edit"));
            ZjcRunStatus.AddChild(REAMSPermissions.ZjcRunStatus.Delete, L("Permission:Delete"));
            //ZjcRunStatus.AddChild(REAMSPermissions.ZjcRunStatus.BatchDelete, L("Permission:BatchDelete"));
            //ZjcRunStatus.AddChild(REAMSPermissions.ZjcRunStatus.ExportExcel, L("Permission:ExportExcel"));

            var IotDeviceLog = ptGroup.AddPermission(REAMSPermissions.IotDeviceLog.Default, L("Permission:IotDeviceLog"));
            IotDeviceLog.AddChild(REAMSPermissions.IotDeviceLog.Query, L("Permission:Query"));
            IotDeviceLog.AddChild(REAMSPermissions.IotDeviceLog.Create, L("Permission:Create"));
            IotDeviceLog.AddChild(REAMSPermissions.IotDeviceLog.Edit, L("Permission:Edit"));
            IotDeviceLog.AddChild(REAMSPermissions.IotDeviceLog.Delete, L("Permission:Delete"));
            //IotDeviceLog.AddChild(REAMSPermissions.IotDeviceLog.BatchDelete, L("Permission:BatchDelete"));
            //IotDeviceLog.AddChild(REAMSPermissions.IotDeviceLog.ExportExcel, L("Permission:ExportExcel"));

            var IotDeviceAlarm = ptGroup.AddPermission(REAMSPermissions.IotDeviceAlarm.Default, L("Permission:IotDeviceAlarm"));
            IotDeviceAlarm.AddChild(REAMSPermissions.IotDeviceAlarm.Query, L("Permission:Query"));
            IotDeviceAlarm.AddChild(REAMSPermissions.IotDeviceAlarm.Create, L("Permission:Create"));
            IotDeviceAlarm.AddChild(REAMSPermissions.IotDeviceAlarm.Edit, L("Permission:Edit"));
            IotDeviceAlarm.AddChild(REAMSPermissions.IotDeviceAlarm.Delete, L("Permission:Delete"));
            //IotDeviceAlarm.AddChild(REAMSPermissions.IotDeviceAlarm.BatchDelete, L("Permission:BatchDelete"));
            //IotDeviceAlarm.AddChild(REAMSPermissions.IotDeviceAlarm.ExportExcel, L("Permission:ExportExcel"));

            var DllRecord = ptGroup.AddPermission(REAMSPermissions.DllRecord.Default, L("Permission:DllRecord"));
            DllRecord.AddChild(REAMSPermissions.DllRecord.Query, L("Permission:Query"));
            DllRecord.AddChild(REAMSPermissions.DllRecord.Create, L("Permission:Create"));
            DllRecord.AddChild(REAMSPermissions.DllRecord.Edit, L("Permission:Edit"));
            DllRecord.AddChild(REAMSPermissions.DllRecord.Delete, L("Permission:Delete"));
            //DllRecord.AddChild(REAMSPermissions.DllRecord.BatchDelete, L("Permission:BatchDelete"));
            //DllRecord.AddChild(REAMSPermissions.DllRecord.ExportExcel, L("Permission:ExportExcel"));

            var DllSetting = ptGroup.AddPermission(REAMSPermissions.DllSetting.Default, L("Permission:DllSetting"));
            DllSetting.AddChild(REAMSPermissions.DllSetting.Query, L("Permission:Query"));
            DllSetting.AddChild(REAMSPermissions.DllSetting.Create, L("Permission:Create"));
            DllSetting.AddChild(REAMSPermissions.DllSetting.Edit, L("Permission:Edit"));
            DllSetting.AddChild(REAMSPermissions.DllSetting.Delete, L("Permission:Delete"));
            //DllSetting.AddChild(REAMSPermissions.DllSetting.BatchDelete, L("Permission:BatchDelete"));
            //DllSetting.AddChild(REAMSPermissions.DllSetting.ExportExcel, L("Permission:ExportExcel"));

            var AtmosphereRecord = ptGroup.AddPermission(REAMSPermissions.AtmosphereRecord.Default, L("Permission:AtmosphereRecord"));
            AtmosphereRecord.AddChild(REAMSPermissions.AtmosphereRecord.Query, L("Permission:Query"));
            AtmosphereRecord.AddChild(REAMSPermissions.AtmosphereRecord.Create, L("Permission:Create"));
            AtmosphereRecord.AddChild(REAMSPermissions.AtmosphereRecord.Edit, L("Permission:Edit"));
            AtmosphereRecord.AddChild(REAMSPermissions.AtmosphereRecord.Delete, L("Permission:Delete"));
            //AtmosphereRecord.AddChild(REAMSPermissions.AtmosphereRecord.BatchDelete, L("Permission:BatchDelete"));
            //AtmosphereRecord.AddChild(REAMSPermissions.AtmosphereRecord.ExportExcel, L("Permission:ExportExcel"));

            var ZcqRunStatus = ptGroup.AddPermission(REAMSPermissions.ZcqRunStatus.Default, L("Permission:ZcqRunStatus"));
            ZcqRunStatus.AddChild(REAMSPermissions.ZcqRunStatus.Query, L("Permission:Query"));
            ZcqRunStatus.AddChild(REAMSPermissions.ZcqRunStatus.Create, L("Permission:Create"));
            ZcqRunStatus.AddChild(REAMSPermissions.ZcqRunStatus.Edit, L("Permission:Edit"));
            ZcqRunStatus.AddChild(REAMSPermissions.ZcqRunStatus.Delete, L("Permission:Delete"));
            //ZcqRunStatus.AddChild(REAMSPermissions.ZcqRunStatus.BatchDelete, L("Permission:BatchDelete"));
            //ZcqRunStatus.AddChild(REAMSPermissions.ZcqRunStatus.ExportExcel, L("Permission:ExportExcel"));

            var ZcqRecord = ptGroup.AddPermission(REAMSPermissions.ZcqRecord.Default, L("Permission:ZcqRecord"));
            ZcqRecord.AddChild(REAMSPermissions.ZcqRecord.Query, L("Permission:Query"));
            ZcqRecord.AddChild(REAMSPermissions.ZcqRecord.Create, L("Permission:Create"));
            ZcqRecord.AddChild(REAMSPermissions.ZcqRecord.Edit, L("Permission:Edit"));
            ZcqRecord.AddChild(REAMSPermissions.ZcqRecord.Delete, L("Permission:Delete"));
            //ZcqRecord.AddChild(REAMSPermissions.ZcqRecord.BatchDelete, L("Permission:BatchDelete"));
            //ZcqRecord.AddChild(REAMSPermissions.ZcqRecord.ExportExcel, L("Permission:ExportExcel"));

            var Device = ptGroup.AddPermission(REAMSPermissions.Device.Default, L("Permission:Device"));
            Device.AddChild(REAMSPermissions.Device.Query, L("Permission:Query"));
            Device.AddChild(REAMSPermissions.Device.Create, L("Permission:Create"));
            Device.AddChild(REAMSPermissions.Device.Edit, L("Permission:Edit"));
            Device.AddChild(REAMSPermissions.Device.Delete, L("Permission:Delete"));
            //Device.AddChild(REAMSPermissions.Device.BatchDelete, L("Permission:BatchDelete"));
            //Device.AddChild(REAMSPermissions.Device.ExportExcel, L("Permission:ExportExcel"));

            var DeviceRoom = ptGroup.AddPermission(REAMSPermissions.DeviceRoom.Default, L("Permission:DeviceRoom"));
            DeviceRoom.AddChild(REAMSPermissions.DeviceRoom.Query, L("Permission:Query"));
            DeviceRoom.AddChild(REAMSPermissions.DeviceRoom.Create, L("Permission:Create"));
            DeviceRoom.AddChild(REAMSPermissions.DeviceRoom.Edit, L("Permission:Edit"));
            DeviceRoom.AddChild(REAMSPermissions.DeviceRoom.Delete, L("Permission:Delete"));
            //DeviceRoom.AddChild(REAMSPermissions.DeviceRoom.BatchDelete, L("Permission:BatchDelete"));
            //DeviceRoom.AddChild(REAMSPermissions.DeviceRoom.ExportExcel, L("Permission:ExportExcel"));

            var Customer = ptGroup.AddPermission(REAMSPermissions.Customer.Default, L("Permission:Customer"));
            Customer.AddChild(REAMSPermissions.Customer.Query, L("Permission:Query"));
            Customer.AddChild(REAMSPermissions.Customer.Create, L("Permission:Create"));
            Customer.AddChild(REAMSPermissions.Customer.Edit, L("Permission:Edit"));
            Customer.AddChild(REAMSPermissions.Customer.Delete, L("Permission:Delete"));
            //Customer.AddChild(REAMSPermissions.Customer.BatchDelete, L("Permission:BatchDelete"));
            //Customer.AddChild(REAMSPermissions.Customer.ExportExcel, L("Permission:ExportExcel"));

            var CustomerService = ptGroup.AddPermission(REAMSPermissions.CustomerService.Default, L("Permission:CustomerService"));
            CustomerService.AddChild(REAMSPermissions.CustomerService.Query, L("Permission:Query"));
            CustomerService.AddChild(REAMSPermissions.CustomerService.Create, L("Permission:Create"));
            CustomerService.AddChild(REAMSPermissions.CustomerService.Edit, L("Permission:Edit"));
            CustomerService.AddChild(REAMSPermissions.CustomerService.Delete, L("Permission:Delete"));
            //CustomerService.AddChild(REAMSPermissions.CustomerService.BatchDelete, L("Permission:BatchDelete"));
            //CustomerService.AddChild(REAMSPermissions.CustomerService.ExportExcel, L("Permission:ExportExcel"));

        }



        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<REAMSResource>(name);
        }
    }
}

