//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.Devices.Dtos
{

    /// <summary>
    /// 设备信息 Dto
    /// </summary>
    public class DevicePagedRequest : PagedAndSortedResultRequestDto
    {
        #region 不保留 基本属性

        ///<summary>
        /// Id
        ///</summary>
        [Display(Name = "Id", Order = 45)]
        public virtual long? Id { get; set; }


        ///<summary>
        /// 站房Id
        ///</summary>
        [Display(Name = "站房Id", Order = 46)]
        public virtual long? DeviceRoomId { get; set; }


        ///<summary>
        /// 客户Id
        ///</summary>
        [Display(Name = "客户Id", Order = 47)]
        public virtual Guid? CustomerId { get; set; }


        ///<summary>
        /// 设备友好名称
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "设备友好名称", Order = 48)]
        public virtual string Name { get; set; }


        ///<summary>
        /// 通讯用户名
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "通讯用户名", Order = 49)]
        public virtual string MqttUserName { get; set; }


        ///<summary>
        /// 设备通讯序列号
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "设备通讯序列号", Order = 51)]
        public virtual string SN { get; set; }


        ///<summary>
        /// 设备名称
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "设备名称", Order = 52)]
        public virtual string ProductName { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 66)]
        public virtual Guid? TenantId { get; set; }


        ///<summary>
        /// 关键字
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "关键字", Order = 67)]
        public virtual string Keyword { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


        /// <summary>
        /// 正常化排序使用
        /// </summary>
        public void Normalize()
        {
            //if (string.IsNullOrEmpty(Sorting))
            //{
            //    Sorting = "Id";
            //}
        }
    }
}