//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.Devices.Dtos
{

    /// <summary>
    /// 设备日志 ListDto
    /// </summary>
    //[AutoMapFrom(typeof(IotDeviceLog))]
public partial class IotDeviceLogListDto : EntityDto<Guid>
    {
        #region 构造方法
        public IotDeviceLogListDto()
        {
        }
        #endregion


        #region 基本属性

        // ///<summary>
        // /// Id
        // ///</summary>
        // [Display(Name = "Id", Order = 10)]
        // public virtual Guid Id { get; set; }


        ///<summary>
        /// 类别
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "类别", Order = 11)]
        public virtual string LogType { get; set; }


        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 12)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 13)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 级别
        ///</summary>
        [Display(Name = "级别", Order = 14)]
        public virtual int Level { get; set; }


        ///<summary>
        /// 消息
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "消息", Order = 15)]
        public virtual string Text { get; set; }


        ///<summary>
        /// 动作
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "动作", Order = 16)]
        public virtual string Act { get; set; }


        ///<summary>
        /// 参数
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "参数", Order = 17)]
        public virtual string Data { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 18)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}