//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.Atm;
using HengDa.LiZongMing.REAMS.Atm.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.Atm
{

    /// <summary>
    /// 气象数据 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.AtmosphereRecord.Default*/)]
    public partial class AtmosphereRecordAppService : REAMSAppServiceBase<AtmosphereRecord, AtmosphereRecordDto, Guid, AtmosphereRecordPagedRequest, AtmosphereRecordDto, AtmosphereRecordDto>, IAtmosphereRecordAppService
    {

        #region 构造方法

        //private readonly AtmosphereRecordManager _atmosphereRecordManager;

        public AtmosphereRecordAppService(
            IAtmosphereRecordRepository repository  //mongodb必须用这个             IRepository<AtmosphereRecord, Guid> repository
            //AtmosphereRecordManager atmosphereRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.AtmosphereRecord.Query;
            //GetListPolicyName = REAMSPermissions.AtmosphereRecord.Query;
            //CreatePolicyName = REAMSPermissions.AtmosphereRecord.Create;
            //UpdatePolicyName = REAMSPermissions.AtmosphereRecord.Edit;
            //DeletePolicyName = REAMSPermissions.AtmosphereRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.AtmosphereRecord.Query)]
        public override Task<AtmosphereRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.AtmosphereRecord.Query)]
        public override Task<PagedResultDto<AtmosphereRecordDto>> GetListAsync(AtmosphereRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.AtmosphereRecord.Create)]
        public async Task<AtmosphereRecordDto> GetOrNew(Nullable<Guid> id)
        {
            AtmosphereRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new AtmosphereRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.AtmosphereRecord.Create)]
        public override async Task<AtmosphereRecordDto> CreateAsync(AtmosphereRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var atmosphereRecord = MapToEntity(input);
            //return MapToGetOutputDto(atmosphereRecord);
        }

        [Authorize(REAMSPermissions.AtmosphereRecord.Edit)]
        public override async Task<AtmosphereRecordDto> UpdateAsync(Guid id, AtmosphereRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var atmosphereRecord = await _atmosphereRecordManager.GetAtmosphereRecordByIdAsync(input.Id);
            //MapToEntity(input, atmosphereRecord);
            //CheckErrors(await _atmosphereRecordManager.UpdateAsync(atmosphereRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _atmosphereRecordManager.SetRoles(atmosphereRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.AtmosphereRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var atmosphereRecord = await _atmosphereRecordManager.GetAtmosphereRecordByIdAsync(id);
            //await _atmosphereRecordManager.DeleteAsync(atmosphereRecord);
        }

        protected override async Task<AtmosphereRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var atmosphereRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (atmosphereRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(AtmosphereRecord), id);
            //}
            //return atmosphereRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="AtmosphereRecord"/> 时转换为 <see cref="AtmosphereRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual AtmosphereRecordDto MapToGetOutputDto(AtmosphereRecord entity)
        {
            //return ObjectMapper.Map<AtmosphereRecord, AtmosphereRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="AtmosphereRecord"/> 时转换为 <see cref="AtmosphereRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<AtmosphereRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override AtmosphereRecord MapToEntity(AtmosphereRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var atmosphereRecord = ObjectMapper.Map<AtmosphereRecord>(createInput);
            //atmosphereRecord.SetNormalizedNames();
            //return atmosphereRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(AtmosphereRecordDto updateInput, AtmosphereRecord atmosphereRecord)
        {
            base.MapToEntity(updateInput, atmosphereRecord);
            //ObjectMapper.Map(updateInput, atmosphereRecord);
            //atmosphereRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<AtmosphereRecord>> CreateFilteredQueryAsync(AtmosphereRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<AtmosphereRecord> ApplySorting(IQueryable<AtmosphereRecord> query, AtmosphereRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}