//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.NBS;
using HengDa.LiZongMing.REAMS.NBS.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.NBS
{

    /// <summary>
    /// 超大气溶胶运行状态 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.NbsRunStatus.Default*/)]
    public partial class NbsRunStatusAppService : REAMSAppServiceBase<NbsRunStatus, NbsRunStatusDto, Guid, NbsRunStatusPagedRequest, NbsRunStatusDto, NbsRunStatusDto>, INbsRunStatusAppService
    {

        #region 构造方法

        //private readonly NbsRunStatusManager _nbsRunStatusManager;

        public NbsRunStatusAppService(
            INbsRunStatusRepository repository  //mongodb必须用这个             IRepository<NbsRunStatus, Guid> repository
            //NbsRunStatusManager nbsRunStatusManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.NbsRunStatus.Query;
            //GetListPolicyName = REAMSPermissions.NbsRunStatus.Query;
            //CreatePolicyName = REAMSPermissions.NbsRunStatus.Create;
            //UpdatePolicyName = REAMSPermissions.NbsRunStatus.Edit;
            //DeletePolicyName = REAMSPermissions.NbsRunStatus.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.NbsRunStatus.Query)]
        public override Task<NbsRunStatusDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.NbsRunStatus.Query)]
        public override Task<PagedResultDto<NbsRunStatusDto>> GetListAsync(NbsRunStatusPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.NbsRunStatus.Create)]
        public async Task<NbsRunStatusDto> GetOrNew(Nullable<Guid> id)
        {
            NbsRunStatusDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new NbsRunStatusDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.NbsRunStatus.Create)]
        public override async Task<NbsRunStatusDto> CreateAsync(NbsRunStatusDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var nbsRunStatus = MapToEntity(input);
            //return MapToGetOutputDto(nbsRunStatus);
        }

        [Authorize(REAMSPermissions.NbsRunStatus.Edit)]
        public override async Task<NbsRunStatusDto> UpdateAsync(Guid id, NbsRunStatusDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var nbsRunStatus = await _nbsRunStatusManager.GetNbsRunStatusByIdAsync(input.Id);
            //MapToEntity(input, nbsRunStatus);
            //CheckErrors(await _nbsRunStatusManager.UpdateAsync(nbsRunStatus));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _nbsRunStatusManager.SetRoles(nbsRunStatus, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.NbsRunStatus.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var nbsRunStatus = await _nbsRunStatusManager.GetNbsRunStatusByIdAsync(id);
            //await _nbsRunStatusManager.DeleteAsync(nbsRunStatus);
        }

        protected override async Task<NbsRunStatus> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var nbsRunStatus = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (nbsRunStatus == null)
            //{
            //    throw new EntityNotFoundException(typeof(NbsRunStatus), id);
            //}
            //return nbsRunStatus;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="NbsRunStatus"/> 时转换为 <see cref="NbsRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual NbsRunStatusDto MapToGetOutputDto(NbsRunStatus entity)
        {
            //return ObjectMapper.Map<NbsRunStatus, NbsRunStatusDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="NbsRunStatus"/> 时转换为 <see cref="NbsRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<NbsRunStatusDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override NbsRunStatus MapToEntity(NbsRunStatusDto createInput)
        {
            return base.MapToEntity(createInput);
            //var nbsRunStatus = ObjectMapper.Map<NbsRunStatus>(createInput);
            //nbsRunStatus.SetNormalizedNames();
            //return nbsRunStatus;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(NbsRunStatusDto updateInput, NbsRunStatus nbsRunStatus)
        {
            base.MapToEntity(updateInput, nbsRunStatus);
            //ObjectMapper.Map(updateInput, nbsRunStatus);
            //nbsRunStatus.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<NbsRunStatus>> CreateFilteredQueryAsync(NbsRunStatusPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.WorkStatusName.Contains(input.Keyword)
                        )
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(!input.WorkStatusName.IsNullOrWhiteSpace(), x => x.WorkStatusName.Contains(input.WorkStatusName))
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.RunUpdateTime.HasValue, x => x.RunUpdateTime == input.RunUpdateTime)
                 .WhereIf(input.AlarmUpdateTime.HasValue, x => x.AlarmUpdateTime == input.AlarmUpdateTime)
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<NbsRunStatus> ApplySorting(IQueryable<NbsRunStatus> query, NbsRunStatusPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}