//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Volo.Abp;
using Volo.Abp.Data;
using Volo.Abp.MongoDB;
using MongoDB.Driver;
//using HengDa.LiZongMing.REAMS.Users;

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.RNS;
using HengDa.LiZongMing.REAMS.Room;
using HengDa.LiZongMing.REAMS.NBS;
using HengDa.LiZongMing.REAMS.NaI;
using HengDa.LiZongMing.REAMS.HVE;
using HengDa.LiZongMing.REAMS.ZJC;
using HengDa.LiZongMing.REAMS.Devices;
using HengDa.LiZongMing.REAMS.DLL;
using HengDa.LiZongMing.REAMS.Atm;
using HengDa.LiZongMing.REAMS.ZCQ;
using HengDa.LiZongMing.REAMS.Crm;


namespace HengDa.LiZongMing.REAMS.MongoDB
{



    /// <summary>
    /// 
    /// </summary>
    public partial interface IREAMSMongoDbContext : IAbpMongoDbContext
    {
        #region 保留  共用的用户属性
        /// <summary>
        /// Users
        /// </summary>
        IMongoCollection<HengDa.LiZongMing.REAMS.Users.AppUser> Users { get;}
        #endregion


        #region 实体

        /// <summary>
        /// 气象数据
        /// </summary>
        IMongoCollection<AtmosphereRecord> AtmosphereRecord { get;}

        /// <summary>
        /// 客户信息
        /// </summary>
        IMongoCollection<Customer> Customer { get;}

        /// <summary>
        /// 工程师信息
        /// </summary>
        IMongoCollection<CustomerService> CustomerService { get;}

        /// <summary>
        /// 设备信息
        /// </summary>
        IMongoCollection<Device> Device { get;}

        /// <summary>
        /// 站房信息
        /// </summary>
        IMongoCollection<DeviceRoom> DeviceRoom { get;}

        /// <summary>
        /// 设备报警记录
        /// </summary>
        IMongoCollection<IotDeviceAlarm> IotDeviceAlarm { get;}

        /// <summary>
        /// 设备日志
        /// </summary>
        IMongoCollection<IotDeviceLog> IotDeviceLog { get;}

        /// <summary>
        /// DLL检测记录
        /// </summary>
        IMongoCollection<DllRecord> DllRecord { get;}

        /// <summary>
        /// DLL设备参数信息
        /// </summary>
        IMongoCollection<DllSetting> DllSetting { get;}

        /// <summary>
        /// 高压电离记录
        /// </summary>
        IMongoCollection<HveExtRecord> HveExtRecord { get;}

        /// <summary>
        /// 高压电离伽马记录
        /// </summary>
        IMongoCollection<HveRecord> HveRecord { get;}

        /// <summary>
        /// 高压电离状态
        /// </summary>
        IMongoCollection<HveRunStatus> HveRunStatus { get;}

        /// <summary>
        /// 碘化纳记录
        /// </summary>
        IMongoCollection<NaiRecord> NaiRecord { get;}

        /// <summary>
        /// 超大气溶胶采样记录
        /// </summary>
        IMongoCollection<NbsRecord> NbsRecord { get;}

        /// <summary>
        /// 超大气溶胶运行状态
        /// </summary>
        IMongoCollection<NbsRunStatus> NbsRunStatus { get;}

        /// <summary>
        /// 降雨状态
        /// </summary>
        IMongoCollection<RnsRunStatus> RnsRunStatus { get;}

        /// <summary>
        /// 站房环境状态
        /// </summary>
        IMongoCollection<RoomRunStatus> RoomRunStatus { get;}

        /// <summary>
        /// 气碘采样记录
        /// </summary>
        IMongoCollection<ZcqRecord> ZcqRecord { get;}

        /// <summary>
        /// 气碘运行状态
        /// </summary>
        IMongoCollection<ZcqRunStatus> ZcqRunStatus { get;}

        /// <summary>
        /// 湿沉降降雨记录
        /// </summary>
        IMongoCollection<ZjcRainRecord> ZjcRainRecord { get;}

        /// <summary>
        /// 干沉降记录
        /// </summary>
        IMongoCollection<ZjcRecord> ZjcRecord { get;}

        /// <summary>
        /// 干湿沉降实时数据
        /// </summary>
        IMongoCollection<ZjcRunStatus> ZjcRunStatus { get;}

        #endregion

    }

}
