//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.RNS;
using HengDa.LiZongMing.REAMS.RNS.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.RNS
{

    /// <summary>
    /// 降雨状态 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.RnsRunStatus.Default*/)]
    public partial class RnsRunStatusAppService : REAMSAppServiceBase<RnsRunStatus, RnsRunStatusDto, Guid, RnsRunStatusPagedRequest, RnsRunStatusDto, RnsRunStatusDto>, IRnsRunStatusAppService
    {

        #region 构造方法

        //private readonly RnsRunStatusManager _rnsRunStatusManager;

        public RnsRunStatusAppService(
            IRnsRunStatusRepository repository  //mongodb必须用这个             IRepository<RnsRunStatus, Guid> repository
            //RnsRunStatusManager rnsRunStatusManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.RnsRunStatus.Query;
            //GetListPolicyName = REAMSPermissions.RnsRunStatus.Query;
            //CreatePolicyName = REAMSPermissions.RnsRunStatus.Create;
            //UpdatePolicyName = REAMSPermissions.RnsRunStatus.Edit;
            //DeletePolicyName = REAMSPermissions.RnsRunStatus.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.RnsRunStatus.Query)]
        public override Task<RnsRunStatusDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.RnsRunStatus.Query)]
        public override Task<PagedResultDto<RnsRunStatusDto>> GetListAsync(RnsRunStatusPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.RnsRunStatus.Create)]
        public async Task<RnsRunStatusDto> GetOrNew(Nullable<Guid> id)
        {
            RnsRunStatusDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new RnsRunStatusDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.RnsRunStatus.Create)]
        public override async Task<RnsRunStatusDto> CreateAsync(RnsRunStatusDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var rnsRunStatus = MapToEntity(input);
            //return MapToGetOutputDto(rnsRunStatus);
        }

        [Authorize(REAMSPermissions.RnsRunStatus.Edit)]
        public override async Task<RnsRunStatusDto> UpdateAsync(Guid id, RnsRunStatusDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var rnsRunStatus = await _rnsRunStatusManager.GetRnsRunStatusByIdAsync(input.Id);
            //MapToEntity(input, rnsRunStatus);
            //CheckErrors(await _rnsRunStatusManager.UpdateAsync(rnsRunStatus));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _rnsRunStatusManager.SetRoles(rnsRunStatus, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.RnsRunStatus.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var rnsRunStatus = await _rnsRunStatusManager.GetRnsRunStatusByIdAsync(id);
            //await _rnsRunStatusManager.DeleteAsync(rnsRunStatus);
        }

        protected override async Task<RnsRunStatus> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var rnsRunStatus = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (rnsRunStatus == null)
            //{
            //    throw new EntityNotFoundException(typeof(RnsRunStatus), id);
            //}
            //return rnsRunStatus;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="RnsRunStatus"/> 时转换为 <see cref="RnsRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual RnsRunStatusDto MapToGetOutputDto(RnsRunStatus entity)
        {
            //return ObjectMapper.Map<RnsRunStatus, RnsRunStatusDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="RnsRunStatus"/> 时转换为 <see cref="RnsRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<RnsRunStatusDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override RnsRunStatus MapToEntity(RnsRunStatusDto createInput)
        {
            return base.MapToEntity(createInput);
            //var rnsRunStatus = ObjectMapper.Map<RnsRunStatus>(createInput);
            //rnsRunStatus.SetNormalizedNames();
            //return rnsRunStatus;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(RnsRunStatusDto updateInput, RnsRunStatus rnsRunStatus)
        {
            base.MapToEntity(updateInput, rnsRunStatus);
            //ObjectMapper.Map(updateInput, rnsRunStatus);
            //rnsRunStatus.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<RnsRunStatus>> CreateFilteredQueryAsync(RnsRunStatusPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<RnsRunStatus> ApplySorting(IQueryable<RnsRunStatus> query, RnsRunStatusPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}