//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.ZCQ;
using HengDa.LiZongMing.REAMS.ZCQ.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.ZCQ
{

    /// <summary>
    /// 气碘采样记录 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.ZcqRecord.Default*/)]
    public partial class ZcqRecordAppService : REAMSAppServiceBase<ZcqRecord, ZcqRecordDto, Guid, ZcqRecordPagedRequest, ZcqRecordDto, ZcqRecordDto>, IZcqRecordAppService
    {

        #region 构造方法

        //private readonly ZcqRecordManager _zcqRecordManager;

        public ZcqRecordAppService(
            IZcqRecordRepository repository  //mongodb必须用这个             IRepository<ZcqRecord, Guid> repository
            //ZcqRecordManager zcqRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.ZcqRecord.Query;
            //GetListPolicyName = REAMSPermissions.ZcqRecord.Query;
            //CreatePolicyName = REAMSPermissions.ZcqRecord.Create;
            //UpdatePolicyName = REAMSPermissions.ZcqRecord.Edit;
            //DeletePolicyName = REAMSPermissions.ZcqRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.ZcqRecord.Query)]
        public override Task<ZcqRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.ZcqRecord.Query)]
        public override Task<PagedResultDto<ZcqRecordDto>> GetListAsync(ZcqRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.ZcqRecord.Create)]
        public async Task<ZcqRecordDto> GetOrNew(Nullable<Guid> id)
        {
            ZcqRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new ZcqRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.ZcqRecord.Create)]
        public override async Task<ZcqRecordDto> CreateAsync(ZcqRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var zcqRecord = MapToEntity(input);
            //return MapToGetOutputDto(zcqRecord);
        }

        [Authorize(REAMSPermissions.ZcqRecord.Edit)]
        public override async Task<ZcqRecordDto> UpdateAsync(Guid id, ZcqRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var zcqRecord = await _zcqRecordManager.GetZcqRecordByIdAsync(input.Id);
            //MapToEntity(input, zcqRecord);
            //CheckErrors(await _zcqRecordManager.UpdateAsync(zcqRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _zcqRecordManager.SetRoles(zcqRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.ZcqRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var zcqRecord = await _zcqRecordManager.GetZcqRecordByIdAsync(id);
            //await _zcqRecordManager.DeleteAsync(zcqRecord);
        }

        protected override async Task<ZcqRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var zcqRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (zcqRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(ZcqRecord), id);
            //}
            //return zcqRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="ZcqRecord"/> 时转换为 <see cref="ZcqRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual ZcqRecordDto MapToGetOutputDto(ZcqRecord entity)
        {
            //return ObjectMapper.Map<ZcqRecord, ZcqRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="ZcqRecord"/> 时转换为 <see cref="ZcqRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<ZcqRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override ZcqRecord MapToEntity(ZcqRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var zcqRecord = ObjectMapper.Map<ZcqRecord>(createInput);
            //zcqRecord.SetNormalizedNames();
            //return zcqRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(ZcqRecordDto updateInput, ZcqRecord zcqRecord)
        {
            base.MapToEntity(updateInput, zcqRecord);
            //ObjectMapper.Map(updateInput, zcqRecord);
            //zcqRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<ZcqRecord>> CreateFilteredQueryAsync(ZcqRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(!input.BatchNumber.IsNullOrWhiteSpace(), x => x.BatchNumber == input.BatchNumber)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<ZcqRecord> ApplySorting(IQueryable<ZcqRecord> query, ZcqRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}