//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;


namespace HengDa.LiZongMing.REAMS.Crm
{

    /// <summary>
    /// 工程师信息
    /// </summary>

    [Table(REAMSDbProperties.DbTablePrefix + "CustomerService")]
    public partial class CustomerService : FullAuditedEntity<Guid>, IMultiTenant  // Entity<Guid> , IHasCreationTime, IHasModificationTime, IExtendableObject, IMustHaveTenant, IContent, IReadPiont, ISeo
    {
        #region 构造方法
        public CustomerService()
        {
        }
        #endregion


        #region 构造方法Guid
        public CustomerService(Guid id) : base(id)
        {
        }
        #endregion


        #region 基本属性

        // ///<summary>
        // /// 编号
        // ///</summary>
        // [Key]
        // [Column(Order = 1)]
        // [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        // [Required()]
        // [Display(Name = "编号", Order = 1)]
        // [UIHint("NotEdit")]
        // public override Guid Id { get; set; }

        ///<summary>
        /// 名称
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "名称", Order = 2)]
        public virtual string Name { get; set; }


        ///<summary>
        /// 公司
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "公司", Order = 3)]
        public virtual string Company { get; set; }


        ///<summary>
        /// 有效状态 
        ///</summary>
        [Display(Name = "有效状态 ", Order = 4)]
        public virtual bool IsEnable { get; set; }


        ///<summary>
        /// 联系人
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "联系人", Order = 5)]
        public virtual string Contact { get; set; }


        ///<summary>
        /// 联系手机
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "联系手机", Order = 6)]
        public virtual string Mobile { get; set; }


        ///<summary>
        /// 联系邮箱
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "联系邮箱", Order = 7)]
        public virtual string Email { get; set; }


        ///<summary>
        /// 联系地址
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "联系地址", Order = 8)]
        public virtual string Address { get; set; }


        ///<summary>
        /// 备注
        ///</summary>
        [MaxLength(2048)]
        [Display(Name = "备注", Order = 9)]
        public virtual string Remark { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 10)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}