//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;


namespace HengDa.LiZongMing.REAMS.DLL
{

    /// <summary>
    /// DLL检测记录
    /// </summary>

    [Table(REAMSDbProperties.DbTablePrefix + "DllRecord")]
    public partial class DllRecord : Entity<Guid>, IHasCreationTime, IMultiTenant  // Entity<Guid> , IHasCreationTime, IHasModificationTime, IExtendableObject, IMustHaveTenant, IContent, IReadPiont, ISeo
    {
        #region 构造方法
        public DllRecord()
        {
        }
        #endregion


        #region 构造方法Guid
        public DllRecord(Guid id) : base(id)
        {
        }
        #endregion


        #region 基本属性

        // ///<summary>
        // /// 编号
        // ///</summary>
        // [Key]
        // [Column(Order = 1)]
        // [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        // [Required()]
        // [Display(Name = "编号", Order = 1)]
        // [UIHint("NotEdit")]
        // public override Guid Id { get; set; }

        ///<summary>
        /// 命令动作
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "命令动作", Order = 2)]
        public virtual string Act { get; set; }


        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 3)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 记录时间
        ///</summary>
        [Display(Name = "记录时间", Order = 4)]
        public virtual long RecordTime { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 5)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 采样模批号
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "采样模批号", Order = 6)]
        public virtual string BatchNumber { get; set; }


        ///<summary>
        /// 是否空白值
        ///</summary>
        [Display(Name = "是否空白值", Order = 7)]
        public virtual bool IsEmpty { get; set; }


        ///<summary>
        /// alpha
        ///</summary>
        [Display(Name = "alpha", Order = 8)]
        public virtual decimal alpha { get; set; }


        ///<summary>
        /// beta0
        ///</summary>
        [Display(Name = "beta0", Order = 9)]
        public virtual decimal beta0 { get; set; }


        ///<summary>
        /// beta2
        ///</summary>
        [Display(Name = "beta2", Order = 10)]
        public virtual decimal beta2 { get; set; }


        ///<summary>
        /// beta
        ///</summary>
        [Display(Name = "beta", Order = 11)]
        public virtual decimal beta { get; set; }


        ///<summary>
        /// β/α比率
        ///</summary>
        [Display(Name = "β/α比率", Order = 12)]
        public virtual decimal ratio { get; set; }


        ///<summary>
        /// 原始数据
        ///</summary>
        [MaxLength(2000)]
        [Display(Name = "原始数据", Order = 13)]
        public virtual string rawData { get; set; }


        ///<summary>
        /// 空气质量指数
        ///</summary>
        [Display(Name = "空气质量指数", Order = 14)]
        public virtual decimal AQI { get; set; }


        ///<summary>
        /// 氟化物浓度
        ///</summary>
        [Display(Name = "氟化物浓度", Order = 15)]
        public virtual decimal Fluoride { get; set; }


        ///<summary>
        /// 污染物1
        ///</summary>
        [Display(Name = "污染物1", Order = 16)]
        public virtual decimal Item1 { get; set; }


        ///<summary>
        /// 污染物2
        ///</summary>
        [Display(Name = "污染物2", Order = 17)]
        public virtual decimal Item2 { get; set; }


        ///<summary>
        /// 温度
        ///</summary>
        [Display(Name = "温度", Order = 18)]
        public virtual decimal Temperature { get; set; }


        ///<summary>
        /// 湿度
        ///</summary>
        [Display(Name = "湿度", Order = 19)]
        public virtual decimal Humidity { get; set; }


        ///<summary>
        /// 气压
        ///</summary>
        [Display(Name = "气压", Order = 20)]
        public virtual decimal Atmosphere { get; set; }


        ///<summary>
        /// 风速 
        ///</summary>
        [Display(Name = "风速 ", Order = 21)]
        public virtual decimal WindSpeed { get; set; }


        ///<summary>
        /// 风向
        ///</summary>
        [Display(Name = "风向", Order = 22)]
        public virtual int WindDirection { get; set; }


        ///<summary>
        /// 雨量
        ///</summary>
        [Display(Name = "雨量", Order = 23)]
        public virtual decimal WaterRequire { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 24)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion

    }
}