//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.NBS.Dtos
{

    /// <summary>
    /// 超大气溶胶采样记录 Dto
    /// </summary>
    //[AutoMapFrom(typeof(NbsRecord))]
public partial class NbsRecordDto : EntityDto<Guid>
    {
        #region 构造方法
        public NbsRecordDto()
        {
        }
        #endregion


        #region 基本属性

        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 1)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 文件号
        ///</summary>
        [Display(Name = "文件号", Order = 2)]
        public virtual int FileNo { get; set; }


        ///<summary>
        /// 滤膜批号
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "滤膜批号", Order = 3)]
        public virtual string BatchNumber { get; set; }


        ///<summary>
        /// 开始时间
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "开始时间", Order = 4)]
        public virtual string StartTime { get; set; }


        ///<summary>
        /// 结束时间
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "结束时间", Order = 5)]
        public virtual string EndTime { get; set; }


        ///<summary>
        /// 瞬时流量
        ///</summary>
        [Display(Name = "瞬时流量", Order = 6)]
        public virtual decimal InstantaneousFlow { get; set; }


        ///<summary>
        /// 标况体积
        ///</summary>
        [Display(Name = "标况体积", Order = 7)]
        public virtual decimal StandardVolume { get; set; }


        ///<summary>
        /// 工况体积
        ///</summary>
        [Display(Name = "工况体积", Order = 8)]
        public virtual decimal WorkingVolume { get; set; }


        ///<summary>
        /// 环境温度
        ///</summary>
        [Display(Name = "环境温度", Order = 9)]
        public virtual decimal Temperature { get; set; }


        ///<summary>
        /// 环境湿度
        ///</summary>
        [Display(Name = "环境湿度", Order = 10)]
        public virtual decimal Humidity { get; set; }


        ///<summary>
        /// 大气压
        ///</summary>
        [Display(Name = "大气压", Order = 11)]
        public virtual decimal Atmosphere { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 12)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 13)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}