//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.Devices;
using HengDa.LiZongMing.REAMS.Devices.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.Devices
{

    /// <summary>
    /// 站房信息 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.DeviceRoom.Default*/)]
    public partial class DeviceRoomAppService : REAMSAppServiceBase<DeviceRoom, DeviceRoomDto, long, DeviceRoomPagedRequest, DeviceRoomDto, DeviceRoomDto>, IDeviceRoomAppService
    {

        #region 构造方法

        //private readonly DeviceRoomManager _deviceRoomManager;

        public DeviceRoomAppService(
            IDeviceRoomRepository repository  //mongodb必须用这个             IRepository<DeviceRoom, long> repository
            //DeviceRoomManager deviceRoomManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.DeviceRoom.Query;
            //GetListPolicyName = REAMSPermissions.DeviceRoom.Query;
            //CreatePolicyName = REAMSPermissions.DeviceRoom.Create;
            //UpdatePolicyName = REAMSPermissions.DeviceRoom.Edit;
            //DeletePolicyName = REAMSPermissions.DeviceRoom.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.DeviceRoom.Query)]
        public override Task<DeviceRoomDto> GetAsync(long id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.DeviceRoom.Query)]
        public override Task<PagedResultDto<DeviceRoomDto>> GetListAsync(DeviceRoomPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.DeviceRoom.Create)]
        public async Task<DeviceRoomDto> GetOrNew(Nullable<long> id)
        {
            DeviceRoomDto editDto = null;

			if (id.HasValue && id.Value > 0 )
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new DeviceRoomDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.DeviceRoom.Create)]
        public override async Task<DeviceRoomDto> CreateAsync(DeviceRoomDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var deviceRoom = MapToEntity(input);
            //return MapToGetOutputDto(deviceRoom);
        }

        [Authorize(REAMSPermissions.DeviceRoom.Edit)]
        public override async Task<DeviceRoomDto> UpdateAsync(long id, DeviceRoomDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var deviceRoom = await _deviceRoomManager.GetDeviceRoomByIdAsync(input.Id);
            //MapToEntity(input, deviceRoom);
            //CheckErrors(await _deviceRoomManager.UpdateAsync(deviceRoom));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _deviceRoomManager.SetRoles(deviceRoom, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.DeviceRoom.Delete)]
        public override  Task DeleteAsync(long id)
        {
            return base.DeleteAsync(id);
            //var deviceRoom = await _deviceRoomManager.GetDeviceRoomByIdAsync(id);
            //await _deviceRoomManager.DeleteAsync(deviceRoom);
        }

        protected override async Task<DeviceRoom> GetEntityByIdAsync(long id)
        {
            return await base.GetEntityByIdAsync(id);
            //var deviceRoom = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (deviceRoom == null)
            //{
            //    throw new EntityNotFoundException(typeof(DeviceRoom), id);
            //}
            //return deviceRoom;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="DeviceRoom"/> 时转换为 <see cref="DeviceRoomDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual DeviceRoomDto MapToGetOutputDto(DeviceRoom entity)
        {
            //return ObjectMapper.Map<DeviceRoom, DeviceRoomDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="DeviceRoom"/> 时转换为 <see cref="DeviceRoomDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<DeviceRoomDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override DeviceRoom MapToEntity(DeviceRoomDto createInput)
        {
            return base.MapToEntity(createInput);
            //var deviceRoom = ObjectMapper.Map<DeviceRoom>(createInput);
            //deviceRoom.SetNormalizedNames();
            //return deviceRoom;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(DeviceRoomDto updateInput, DeviceRoom deviceRoom)
        {
            base.MapToEntity(updateInput, deviceRoom);
            //ObjectMapper.Map(updateInput, deviceRoom);
            //deviceRoom.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<DeviceRoom>> CreateFilteredQueryAsync(DeviceRoomPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Name.Contains(input.Keyword)
                        || x.ShortName.Contains(input.Keyword)
                        || x.MqttUserName.Contains(input.Keyword)
                        || x.HWConnectionJson.Contains(input.Keyword)
                        || x.Remark.Contains(input.Keyword)
                        )
                 .WhereIf(!input.Name.IsNullOrWhiteSpace(), x => x.Name.Contains(input.Name))
                 .WhereIf(!input.ShortName.IsNullOrWhiteSpace(), x => x.ShortName.Contains(input.ShortName))
                 .WhereIf(!input.MqttUserName.IsNullOrWhiteSpace(), x => x.MqttUserName.Contains(input.MqttUserName))
                 .WhereIf(!input.SN.IsNullOrWhiteSpace(), x => x.SN == input.SN)
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<DeviceRoom> ApplySorting(IQueryable<DeviceRoom> query, DeviceRoomPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}