//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.Devices;
using HengDa.LiZongMing.REAMS.Devices.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.Devices
{

    /// <summary>
    /// 设备日志 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.IotDeviceLog.Default*/)]
    public partial class IotDeviceLogAppService : REAMSAppServiceBase<IotDeviceLog, IotDeviceLogDto, Guid, IotDeviceLogPagedRequest, IotDeviceLogDto, IotDeviceLogDto>, IIotDeviceLogAppService
    {

        #region 构造方法

        //private readonly IotDeviceLogManager _iotDeviceLogManager;

        public IotDeviceLogAppService(
            IIotDeviceLogRepository repository  //mongodb必须用这个             IRepository<IotDeviceLog, Guid> repository
            //IotDeviceLogManager iotDeviceLogManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.IotDeviceLog.Query;
            //GetListPolicyName = REAMSPermissions.IotDeviceLog.Query;
            //CreatePolicyName = REAMSPermissions.IotDeviceLog.Create;
            //UpdatePolicyName = REAMSPermissions.IotDeviceLog.Edit;
            //DeletePolicyName = REAMSPermissions.IotDeviceLog.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.IotDeviceLog.Query)]
        public override Task<IotDeviceLogDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.IotDeviceLog.Query)]
        public override Task<PagedResultDto<IotDeviceLogDto>> GetListAsync(IotDeviceLogPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.IotDeviceLog.Create)]
        public async Task<IotDeviceLogDto> GetOrNew(Nullable<Guid> id)
        {
            IotDeviceLogDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new IotDeviceLogDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.IotDeviceLog.Create)]
        public override async Task<IotDeviceLogDto> CreateAsync(IotDeviceLogDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var iotDeviceLog = MapToEntity(input);
            //return MapToGetOutputDto(iotDeviceLog);
        }

        [Authorize(REAMSPermissions.IotDeviceLog.Edit)]
        public override async Task<IotDeviceLogDto> UpdateAsync(Guid id, IotDeviceLogDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var iotDeviceLog = await _iotDeviceLogManager.GetIotDeviceLogByIdAsync(input.Id);
            //MapToEntity(input, iotDeviceLog);
            //CheckErrors(await _iotDeviceLogManager.UpdateAsync(iotDeviceLog));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _iotDeviceLogManager.SetRoles(iotDeviceLog, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.IotDeviceLog.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var iotDeviceLog = await _iotDeviceLogManager.GetIotDeviceLogByIdAsync(id);
            //await _iotDeviceLogManager.DeleteAsync(iotDeviceLog);
        }

        protected override async Task<IotDeviceLog> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var iotDeviceLog = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (iotDeviceLog == null)
            //{
            //    throw new EntityNotFoundException(typeof(IotDeviceLog), id);
            //}
            //return iotDeviceLog;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="IotDeviceLog"/> 时转换为 <see cref="IotDeviceLogDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual IotDeviceLogDto MapToGetOutputDto(IotDeviceLog entity)
        {
            //return ObjectMapper.Map<IotDeviceLog, IotDeviceLogDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="IotDeviceLog"/> 时转换为 <see cref="IotDeviceLogDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<IotDeviceLogDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override IotDeviceLog MapToEntity(IotDeviceLogDto createInput)
        {
            return base.MapToEntity(createInput);
            //var iotDeviceLog = ObjectMapper.Map<IotDeviceLog>(createInput);
            //iotDeviceLog.SetNormalizedNames();
            //return iotDeviceLog;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(IotDeviceLogDto updateInput, IotDeviceLog iotDeviceLog)
        {
            base.MapToEntity(updateInput, iotDeviceLog);
            //ObjectMapper.Map(updateInput, iotDeviceLog);
            //iotDeviceLog.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<IotDeviceLog>> CreateFilteredQueryAsync(IotDeviceLogPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Text.Contains(input.Keyword)
                        || x.Data.Contains(input.Keyword)
                        )
                 .WhereIf(input.Id.HasValue, x => x.Id == input.Id)
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.Level.HasValue, x => x.Level == input.Level)
                 .WhereIf(!input.Act.IsNullOrWhiteSpace(), x => x.Act == input.Act)
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<IotDeviceLog> ApplySorting(IQueryable<IotDeviceLog> query, IotDeviceLogPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}