//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.NaI;
using HengDa.LiZongMing.REAMS.NaI.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.NaI
{

    /// <summary>
    /// 碘化纳记录 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.NaiRecord.Default*/)]
    public partial class NaiRecordAppService : REAMSAppServiceBase<NaiRecord, NaiRecordDto, Guid, NaiRecordPagedRequest, NaiRecordDto, NaiRecordDto>, INaiRecordAppService
    {

        #region 构造方法

        //private readonly NaiRecordManager _naiRecordManager;

        public NaiRecordAppService(
            INaiRecordRepository repository  //mongodb必须用这个             IRepository<NaiRecord, Guid> repository
            //NaiRecordManager naiRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.NaiRecord.Query;
            //GetListPolicyName = REAMSPermissions.NaiRecord.Query;
            //CreatePolicyName = REAMSPermissions.NaiRecord.Create;
            //UpdatePolicyName = REAMSPermissions.NaiRecord.Edit;
            //DeletePolicyName = REAMSPermissions.NaiRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.NaiRecord.Query)]
        public override Task<NaiRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.NaiRecord.Query)]
        public override Task<PagedResultDto<NaiRecordDto>> GetListAsync(NaiRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.NaiRecord.Create)]
        public async Task<NaiRecordDto> GetOrNew(Nullable<Guid> id)
        {
            NaiRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new NaiRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.NaiRecord.Create)]
        public override async Task<NaiRecordDto> CreateAsync(NaiRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var naiRecord = MapToEntity(input);
            //return MapToGetOutputDto(naiRecord);
        }

        [Authorize(REAMSPermissions.NaiRecord.Edit)]
        public override async Task<NaiRecordDto> UpdateAsync(Guid id, NaiRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var naiRecord = await _naiRecordManager.GetNaiRecordByIdAsync(input.Id);
            //MapToEntity(input, naiRecord);
            //CheckErrors(await _naiRecordManager.UpdateAsync(naiRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _naiRecordManager.SetRoles(naiRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.NaiRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var naiRecord = await _naiRecordManager.GetNaiRecordByIdAsync(id);
            //await _naiRecordManager.DeleteAsync(naiRecord);
        }

        protected override async Task<NaiRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var naiRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (naiRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(NaiRecord), id);
            //}
            //return naiRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="NaiRecord"/> 时转换为 <see cref="NaiRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual NaiRecordDto MapToGetOutputDto(NaiRecord entity)
        {
            //return ObjectMapper.Map<NaiRecord, NaiRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="NaiRecord"/> 时转换为 <see cref="NaiRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<NaiRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override NaiRecord MapToEntity(NaiRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var naiRecord = ObjectMapper.Map<NaiRecord>(createInput);
            //naiRecord.SetNormalizedNames();
            //return naiRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(NaiRecordDto updateInput, NaiRecord naiRecord)
        {
            base.MapToEntity(updateInput, naiRecord);
            //ObjectMapper.Map(updateInput, naiRecord);
            //naiRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<NaiRecord>> CreateFilteredQueryAsync(NaiRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.xml.Contains(input.Keyword)
                        )
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<NaiRecord> ApplySorting(IQueryable<NaiRecord> query, NaiRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}