//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.ZJC;
using HengDa.LiZongMing.REAMS.ZJC.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.ZJC
{

    /// <summary>
    /// 湿沉降降雨记录 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.ZjcRainRecord.Default*/)]
    public partial class ZjcRainRecordAppService : REAMSAppServiceBase<ZjcRainRecord, ZjcRainRecordDto, Guid, ZjcRainRecordPagedRequest, ZjcRainRecordDto, ZjcRainRecordDto>, IZjcRainRecordAppService
    {

        #region 构造方法

        //private readonly ZjcRainRecordManager _zjcRainRecordManager;

        public ZjcRainRecordAppService(
            IZjcRainRecordRepository repository  //mongodb必须用这个             IRepository<ZjcRainRecord, Guid> repository
            //ZjcRainRecordManager zjcRainRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.ZjcRainRecord.Query;
            //GetListPolicyName = REAMSPermissions.ZjcRainRecord.Query;
            //CreatePolicyName = REAMSPermissions.ZjcRainRecord.Create;
            //UpdatePolicyName = REAMSPermissions.ZjcRainRecord.Edit;
            //DeletePolicyName = REAMSPermissions.ZjcRainRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.ZjcRainRecord.Query)]
        public override Task<ZjcRainRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.ZjcRainRecord.Query)]
        public override Task<PagedResultDto<ZjcRainRecordDto>> GetListAsync(ZjcRainRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.ZjcRainRecord.Create)]
        public async Task<ZjcRainRecordDto> GetOrNew(Nullable<Guid> id)
        {
            ZjcRainRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new ZjcRainRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.ZjcRainRecord.Create)]
        public override async Task<ZjcRainRecordDto> CreateAsync(ZjcRainRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var zjcRainRecord = MapToEntity(input);
            //return MapToGetOutputDto(zjcRainRecord);
        }

        [Authorize(REAMSPermissions.ZjcRainRecord.Edit)]
        public override async Task<ZjcRainRecordDto> UpdateAsync(Guid id, ZjcRainRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var zjcRainRecord = await _zjcRainRecordManager.GetZjcRainRecordByIdAsync(input.Id);
            //MapToEntity(input, zjcRainRecord);
            //CheckErrors(await _zjcRainRecordManager.UpdateAsync(zjcRainRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _zjcRainRecordManager.SetRoles(zjcRainRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.ZjcRainRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var zjcRainRecord = await _zjcRainRecordManager.GetZjcRainRecordByIdAsync(id);
            //await _zjcRainRecordManager.DeleteAsync(zjcRainRecord);
        }

        protected override async Task<ZjcRainRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var zjcRainRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (zjcRainRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(ZjcRainRecord), id);
            //}
            //return zjcRainRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="ZjcRainRecord"/> 时转换为 <see cref="ZjcRainRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual ZjcRainRecordDto MapToGetOutputDto(ZjcRainRecord entity)
        {
            //return ObjectMapper.Map<ZjcRainRecord, ZjcRainRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="ZjcRainRecord"/> 时转换为 <see cref="ZjcRainRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<ZjcRainRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override ZjcRainRecord MapToEntity(ZjcRainRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var zjcRainRecord = ObjectMapper.Map<ZjcRainRecord>(createInput);
            //zjcRainRecord.SetNormalizedNames();
            //return zjcRainRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(ZjcRainRecordDto updateInput, ZjcRainRecord zjcRainRecord)
        {
            base.MapToEntity(updateInput, zjcRainRecord);
            //ObjectMapper.Map(updateInput, zjcRainRecord);
            //zjcRainRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<ZjcRainRecord>> CreateFilteredQueryAsync(ZjcRainRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<ZjcRainRecord> ApplySorting(IQueryable<ZjcRainRecord> query, ZjcRainRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}