//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.ZJC;
using HengDa.LiZongMing.REAMS.ZJC.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.ZJC
{

    /// <summary>
    /// 干湿沉降实时数据 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.ZjcRunStatus.Default*/)]
    public partial class ZjcRunStatusAppService : REAMSAppServiceBase<ZjcRunStatus, ZjcRunStatusDto, Guid, ZjcRunStatusPagedRequest, ZjcRunStatusDto, ZjcRunStatusDto>, IZjcRunStatusAppService
    {

        #region 构造方法

        //private readonly ZjcRunStatusManager _zjcRunStatusManager;

        public ZjcRunStatusAppService(
            IZjcRunStatusRepository repository  //mongodb必须用这个             IRepository<ZjcRunStatus, Guid> repository
            //ZjcRunStatusManager zjcRunStatusManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.ZjcRunStatus.Query;
            //GetListPolicyName = REAMSPermissions.ZjcRunStatus.Query;
            //CreatePolicyName = REAMSPermissions.ZjcRunStatus.Create;
            //UpdatePolicyName = REAMSPermissions.ZjcRunStatus.Edit;
            //DeletePolicyName = REAMSPermissions.ZjcRunStatus.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.ZjcRunStatus.Query)]
        public override Task<ZjcRunStatusDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.ZjcRunStatus.Query)]
        public override Task<PagedResultDto<ZjcRunStatusDto>> GetListAsync(ZjcRunStatusPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.ZjcRunStatus.Create)]
        public async Task<ZjcRunStatusDto> GetOrNew(Nullable<Guid> id)
        {
            ZjcRunStatusDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new ZjcRunStatusDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.ZjcRunStatus.Create)]
        public override async Task<ZjcRunStatusDto> CreateAsync(ZjcRunStatusDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var zjcRunStatus = MapToEntity(input);
            //return MapToGetOutputDto(zjcRunStatus);
        }

        [Authorize(REAMSPermissions.ZjcRunStatus.Edit)]
        public override async Task<ZjcRunStatusDto> UpdateAsync(Guid id, ZjcRunStatusDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var zjcRunStatus = await _zjcRunStatusManager.GetZjcRunStatusByIdAsync(input.Id);
            //MapToEntity(input, zjcRunStatus);
            //CheckErrors(await _zjcRunStatusManager.UpdateAsync(zjcRunStatus));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _zjcRunStatusManager.SetRoles(zjcRunStatus, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.ZjcRunStatus.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var zjcRunStatus = await _zjcRunStatusManager.GetZjcRunStatusByIdAsync(id);
            //await _zjcRunStatusManager.DeleteAsync(zjcRunStatus);
        }

        protected override async Task<ZjcRunStatus> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var zjcRunStatus = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (zjcRunStatus == null)
            //{
            //    throw new EntityNotFoundException(typeof(ZjcRunStatus), id);
            //}
            //return zjcRunStatus;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="ZjcRunStatus"/> 时转换为 <see cref="ZjcRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual ZjcRunStatusDto MapToGetOutputDto(ZjcRunStatus entity)
        {
            //return ObjectMapper.Map<ZjcRunStatus, ZjcRunStatusDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="ZjcRunStatus"/> 时转换为 <see cref="ZjcRunStatusDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<ZjcRunStatusDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override ZjcRunStatus MapToEntity(ZjcRunStatusDto createInput)
        {
            return base.MapToEntity(createInput);
            //var zjcRunStatus = ObjectMapper.Map<ZjcRunStatus>(createInput);
            //zjcRunStatus.SetNormalizedNames();
            //return zjcRunStatus;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(ZjcRunStatusDto updateInput, ZjcRunStatus zjcRunStatus)
        {
            base.MapToEntity(updateInput, zjcRunStatus);
            //ObjectMapper.Map(updateInput, zjcRunStatus);
            //zjcRunStatus.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<ZjcRunStatus>> CreateFilteredQueryAsync(ZjcRunStatusPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<ZjcRunStatus> ApplySorting(IQueryable<ZjcRunStatus> query, ZjcRunStatusPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}