//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.ZJC;
using HengDa.LiZongMing.REAMS.ZJC.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.ZJC
{

    /// <summary>
    /// 干沉降记录 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.ZjcRecord.Default*/)]
    public partial class ZjcRecordAppService : REAMSAppServiceBase<ZjcRecord, ZjcRecordDto, Guid, ZjcRecordPagedRequest, ZjcRecordDto, ZjcRecordDto>, IZjcRecordAppService
    {

        #region 构造方法

        //private readonly ZjcRecordManager _zjcRecordManager;

        public ZjcRecordAppService(
            IZjcRecordRepository repository  //mongodb必须用这个             IRepository<ZjcRecord, Guid> repository
            //ZjcRecordManager zjcRecordManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.ZjcRecord.Query;
            //GetListPolicyName = REAMSPermissions.ZjcRecord.Query;
            //CreatePolicyName = REAMSPermissions.ZjcRecord.Create;
            //UpdatePolicyName = REAMSPermissions.ZjcRecord.Edit;
            //DeletePolicyName = REAMSPermissions.ZjcRecord.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.ZjcRecord.Query)]
        public override Task<ZjcRecordDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.ZjcRecord.Query)]
        public override Task<PagedResultDto<ZjcRecordDto>> GetListAsync(ZjcRecordPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.ZjcRecord.Create)]
        public async Task<ZjcRecordDto> GetOrNew(Nullable<Guid> id)
        {
            ZjcRecordDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new ZjcRecordDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.ZjcRecord.Create)]
        public override async Task<ZjcRecordDto> CreateAsync(ZjcRecordDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var zjcRecord = MapToEntity(input);
            //return MapToGetOutputDto(zjcRecord);
        }

        [Authorize(REAMSPermissions.ZjcRecord.Edit)]
        public override async Task<ZjcRecordDto> UpdateAsync(Guid id, ZjcRecordDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var zjcRecord = await _zjcRecordManager.GetZjcRecordByIdAsync(input.Id);
            //MapToEntity(input, zjcRecord);
            //CheckErrors(await _zjcRecordManager.UpdateAsync(zjcRecord));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _zjcRecordManager.SetRoles(zjcRecord, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.ZjcRecord.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var zjcRecord = await _zjcRecordManager.GetZjcRecordByIdAsync(id);
            //await _zjcRecordManager.DeleteAsync(zjcRecord);
        }

        protected override async Task<ZjcRecord> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var zjcRecord = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (zjcRecord == null)
            //{
            //    throw new EntityNotFoundException(typeof(ZjcRecord), id);
            //}
            //return zjcRecord;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="ZjcRecord"/> 时转换为 <see cref="ZjcRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual ZjcRecordDto MapToGetOutputDto(ZjcRecord entity)
        {
            //return ObjectMapper.Map<ZjcRecord, ZjcRecordDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="ZjcRecord"/> 时转换为 <see cref="ZjcRecordDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<ZjcRecordDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override ZjcRecord MapToEntity(ZjcRecordDto createInput)
        {
            return base.MapToEntity(createInput);
            //var zjcRecord = ObjectMapper.Map<ZjcRecord>(createInput);
            //zjcRecord.SetNormalizedNames();
            //return zjcRecord;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(ZjcRecordDto updateInput, ZjcRecord zjcRecord)
        {
            base.MapToEntity(updateInput, zjcRecord);
            //ObjectMapper.Map(updateInput, zjcRecord);
            //zjcRecord.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<ZjcRecord>> CreateFilteredQueryAsync(ZjcRecordPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(input.DeviceId.HasValue, x => x.DeviceId == input.DeviceId)
                 .WhereIf(input.TimeStart.HasValue, x => x.CreationTime >= input.TimeStart)
                 .WhereIf(input.TimeEnd.HasValue, x => x.CreationTime < input.TimeEnd) 
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<ZjcRecord> ApplySorting(IQueryable<ZjcRecord> query, ZjcRecordPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}