//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.Crm.Dtos
{

    /// <summary>
    /// 工程师信息 Dto
    /// </summary>
    public class CustomerServicePagedRequest : PagedAndSortedResultRequestDto
    {
        #region 不保留 基本属性

        ///<summary>
        /// 名称
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "名称", Order = 22)]
        public virtual string Name { get; set; }


        ///<summary>
        /// 有效状态 
        ///</summary>
        [Display(Name = "有效状态 ", Order = 24)]
        public virtual bool? IsEnable { get; set; }


        ///<summary>
        /// 联系手机
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "联系手机", Order = 26)]
        public virtual string Mobile { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 30)]
        public virtual Guid? TenantId { get; set; }


        ///<summary>
        /// 关键字
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "关键字", Order = 31)]
        public virtual string Keyword { get; set; }


        #endregion

        #region 保留  手动添加属性



        #endregion


        /// <summary>
        /// 正常化排序使用
        /// </summary>
        public void Normalize()
        {
            //if (string.IsNullOrEmpty(Sorting))
            //{
            //    Sorting = "Id";
            //}
        }
    }
}