//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore.Modeling;
using Volo.Abp.Identity;
using Volo.Abp.Users.EntityFrameworkCore;
using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.RNS;
using HengDa.LiZongMing.REAMS.Room;
using HengDa.LiZongMing.REAMS.NBS;
using HengDa.LiZongMing.REAMS.NaI;
using HengDa.LiZongMing.REAMS.HVE;
using HengDa.LiZongMing.REAMS.ZJC;
using HengDa.LiZongMing.REAMS.Devices;
using HengDa.LiZongMing.REAMS.DLL;
using HengDa.LiZongMing.REAMS.Atm;
using HengDa.LiZongMing.REAMS.ZCQ;
using HengDa.LiZongMing.REAMS.Crm;


namespace HengDa.LiZongMing.REAMS.EntityFrameworkCore
{



    /// <summary>
    /// 
    /// </summary>
    public partial interface IREAMSDbContext : IAbpEfCoreDbContext
    {
        #region 保留  共用的用户属性
        /// <summary>
        /// Users
        /// </summary>
        DbSet<HengDa.LiZongMing.REAMS.Users.AppUser> Users { get; set; }
        #endregion


        #region 实体

        /// <summary>
        /// 气象数据
        /// </summary>
        DbSet<AtmosphereRecord> AtmosphereRecords { get; set; }

        /// <summary>
        /// 客户信息
        /// </summary>
        DbSet<Customer> Customers { get; set; }

        /// <summary>
        /// 工程师信息
        /// </summary>
        DbSet<CustomerService> CustomerServices { get; set; }

        /// <summary>
        /// 设备信息
        /// </summary>
        DbSet<Device> Devices { get; set; }

        /// <summary>
        /// 站房信息
        /// </summary>
        DbSet<DeviceRoom> DeviceRooms { get; set; }

        /// <summary>
        /// 设备报警记录
        /// </summary>
        DbSet<IotDeviceAlarm> IotDeviceAlarms { get; set; }

        /// <summary>
        /// 设备日志
        /// </summary>
        DbSet<IotDeviceLog> IotDeviceLogs { get; set; }

        /// <summary>
        /// DLL检测记录
        /// </summary>
        DbSet<DllRecord> DllRecords { get; set; }

        /// <summary>
        /// DLL设备参数信息
        /// </summary>
        DbSet<DllSetting> DllSettings { get; set; }

        /// <summary>
        /// 高压电离记录
        /// </summary>
        DbSet<HveExtRecord> HveExtRecords { get; set; }

        /// <summary>
        /// 高压电离伽马记录
        /// </summary>
        DbSet<HveRecord> HveRecords { get; set; }

        /// <summary>
        /// 高压电离状态
        /// </summary>
        DbSet<HveRunStatus> HveRunStatuss { get; set; }

        /// <summary>
        /// 碘化纳记录
        /// </summary>
        DbSet<NaiRecord> NaiRecords { get; set; }

        /// <summary>
        /// 超大气溶胶采样记录
        /// </summary>
        DbSet<NbsRecord> NbsRecords { get; set; }

        /// <summary>
        /// 超大气溶胶运行状态
        /// </summary>
        DbSet<NbsRunStatus> NbsRunStatuss { get; set; }

        /// <summary>
        /// 降雨状态
        /// </summary>
        DbSet<RnsRunStatus> RnsRunStatuss { get; set; }

        /// <summary>
        /// 站房环境状态
        /// </summary>
        DbSet<RoomRunStatus> RoomRunStatuss { get; set; }

        /// <summary>
        /// 气碘采样记录
        /// </summary>
        DbSet<ZcqRecord> ZcqRecords { get; set; }

        /// <summary>
        /// 气碘运行状态
        /// </summary>
        DbSet<ZcqRunStatus> ZcqRunStatuss { get; set; }

        /// <summary>
        /// 湿沉降降雨记录
        /// </summary>
        DbSet<ZjcRainRecord> ZjcRainRecords { get; set; }

        /// <summary>
        /// 干沉降记录
        /// </summary>
        DbSet<ZjcRecord> ZjcRecords { get; set; }

        /// <summary>
        /// 干湿沉降实时数据
        /// </summary>
        DbSet<ZjcRunStatus> ZjcRunStatuss { get; set; }

        #endregion

    }

}
