//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore.Modeling;
using Volo.Abp.Identity;
using Volo.Abp.Users.EntityFrameworkCore;
using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.RNS;
using HengDa.LiZongMing.REAMS.Room;
using HengDa.LiZongMing.REAMS.NBS;
using HengDa.LiZongMing.REAMS.NaI;
using HengDa.LiZongMing.REAMS.HVE;
using HengDa.LiZongMing.REAMS.ZJC;
using HengDa.LiZongMing.REAMS.Devices;
using HengDa.LiZongMing.REAMS.DLL;
using HengDa.LiZongMing.REAMS.Atm;
using HengDa.LiZongMing.REAMS.ZCQ;
using HengDa.LiZongMing.REAMS.Crm;


namespace HengDa.LiZongMing.REAMS.EntityFrameworkCore
{



    /// <summary>
    /// 
    /// </summary>
    [ConnectionStringName(REAMSDbProperties.ConnectionStringName)]
    public partial class REAMSDbContext : AbpDbContext<REAMSDbContext> , IREAMSDbContext
    {

        #region 基本
        public REAMSDbContext(DbContextOptions<REAMSDbContext> options)
            : base(options)
        {

        }

        #endregion



        #region OnModelCreating
        protected override void OnModelCreating(ModelBuilder builder)
        {

            base.OnModelCreating(builder);

            /* Configure the shared tables (with included modules) here */
            #region 保留  共用的用户属性CreateModel
            builder.Entity<HengDa.LiZongMing.REAMS.Users.AppUser>(b =>
            {
                b.ToTable(AbpIdentityDbProperties.DbTablePrefix + "Users"); //Sharing the same table "AbpUsers" with the IdentityUser


                b.ConfigureByConvention();
                b.ConfigureAbpUser();

                /* Configure mappings for your additional properties
                 * Also see the YunEfCoreEntityExtensionMappings class
                 */
            });
            #endregion

            builder.Entity<HengDa.LiZongMing.REAMS.Template.AppTemplate>(b =>
            {
                b.ToTable("abproles");
                b.ConfigureByConvention();
                b.Property(x => x.IsAddSegment);

            });
            builder.Entity<HengDa.LiZongMing.REAMS.Template.AppTemplate>().Ignore(p => p.IsAddSegment);

            /* Configure your own tables/entities inside the ConfigureYun method */
            //builder.Entity<HengDa.LiZongMing.REAMS.Template.AppTemplate>(b =>
            //{
            //    b.ToTable("iot_nairecord");
            //    b.ConfigureByConvention();
            //    b.Property(x => x.AddSegment);

            //});
            builder.ConfigureREAMS();

        }

        #endregion

    }

}
