//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.Atm.Dtos
{

    /// <summary>
    /// 气象数据 Dto
    /// </summary>
    //[AutoMapFrom(typeof(AtmosphereRecord))]
public partial class AtmosphereRecordDto : EntityDto<Guid>
    {
        #region 构造方法
        public AtmosphereRecordDto()
        {
        }
        #endregion


        #region 基本属性

        // ///<summary>
        // /// Id
        // ///</summary>
        // [Display(Name = "Id", Order = 1)]
        // public virtual Guid Id { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 2)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 3)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 地理位置-经度
        ///</summary>
        [Display(Name = "地理位置-经度", Order = 4)]
        public virtual decimal GeoLocation_Lng { get; set; }


        ///<summary>
        /// 地理位置-伟度
        ///</summary>
        [Display(Name = "地理位置-伟度", Order = 5)]
        public virtual decimal GeoLocation_Lat { get; set; }


        ///<summary>
        /// 大气温度(℃)
        ///</summary>
        [Display(Name = "大气温度(℃)", Order = 6)]
        public virtual decimal Temperature { get; set; }


        ///<summary>
        /// 大气湿度(%RH)
        ///</summary>
        [Display(Name = "大气湿度(%RH)", Order = 7)]
        public virtual decimal Humidity { get; set; }


        ///<summary>
        /// 大气气压(hpa)
        ///</summary>
        [Display(Name = "大气气压(hpa)", Order = 8)]
        public virtual decimal Atmosphere { get; set; }


        ///<summary>
        /// 风速(m/s)
        ///</summary>
        [Display(Name = "风速(m/s)", Order = 9)]
        public virtual decimal WindSpeed { get; set; }


        ///<summary>
        /// 风向(°)
        ///</summary>
        [Display(Name = "风向(°)", Order = 10)]
        public virtual decimal WindDirection { get; set; }


        ///<summary>
        /// 噪声(dB)
        ///</summary>
        [Display(Name = "噪声(dB)", Order = 11)]
        public virtual decimal Noise { get; set; }


        ///<summary>
        /// CO (μg/m3)
        ///</summary>
        [Display(Name = "CO (μg/m3)", Order = 12)]
        public virtual decimal CO { get; set; }


        ///<summary>
        /// SO2(μg/m3)
        ///</summary>
        [Display(Name = "SO2(μg/m3)", Order = 13)]
        public virtual decimal SO2 { get; set; }


        ///<summary>
        /// O3(μg/m3)
        ///</summary>
        [Display(Name = "O3(μg/m3)", Order = 14)]
        public virtual decimal O3 { get; set; }


        ///<summary>
        /// O3_滚动8小平均(μg/m3)
        ///</summary>
        [Display(Name = "O3_滚动8小平均(μg/m3)", Order = 15)]
        public virtual decimal? O3_Avg8H { get; set; }


        ///<summary>
        /// NO2(μg/m3)
        ///</summary>
        [Display(Name = "NO2(μg/m3)", Order = 16)]
        public virtual decimal NO2 { get; set; }


        ///<summary>
        /// TVOC(μg/m3)
        ///</summary>
        [Display(Name = "TVOC(μg/m3)", Order = 17)]
        public virtual decimal VOC { get; set; }


        ///<summary>
        /// PM10(μg/m3)
        ///</summary>
        [Display(Name = "PM10(μg/m3)", Order = 18)]
        public virtual decimal PM10 { get; set; }


        ///<summary>
        /// PM2.5(μg/m3)
        ///</summary>
        [Display(Name = "PM2.5(μg/m3)", Order = 19)]
        public virtual decimal PM2_5 { get; set; }


        ///<summary>
        /// NH3(μg/m3)
        ///</summary>
        [Display(Name = "NH3(μg/m3)", Order = 20)]
        public virtual decimal NH3 { get; set; }


        ///<summary>
        /// HCL (μg/m3)
        ///</summary>
        [Display(Name = "HCL (μg/m3)", Order = 21)]
        public virtual decimal HCL { get; set; }


        ///<summary>
        /// CL2(μg/m3)
        ///</summary>
        [Display(Name = "CL2(μg/m3)", Order = 22)]
        public virtual decimal CL2 { get; set; }


        ///<summary>
        /// C2H4O2(μg/m3)
        ///</summary>
        [Display(Name = "C2H4O2(μg/m3)", Order = 23)]
        public virtual decimal C2H4O2 { get; set; }


        ///<summary>
        /// C6H6(μg/m3)
        ///</summary>
        [Display(Name = "C6H6(μg/m3)", Order = 24)]
        public virtual decimal C6H6 { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 25)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion



    }
}