//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.Room.Dtos
{

    /// <summary>
    /// 站房环境状态 Dto
    /// </summary>
    //[AutoMapFrom(typeof(RoomRunStatus))]
public partial class RoomRunStatusDto : EntityDto<Guid>
    {
        #region 构造方法
        public RoomRunStatusDto()
        {
        }
        #endregion


        #region 基本属性

        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 1)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 地理位置-经度
        ///</summary>
        [Display(Name = "地理位置-经度", Order = 2)]
        public virtual decimal GeoLocation_Lng { get; set; }


        ///<summary>
        /// 地理位置-伟度
        ///</summary>
        [Display(Name = "地理位置-伟度", Order = 3)]
        public virtual decimal GeoLocation_Lat { get; set; }


        ///<summary>
        /// 地理位置-海拔高度
        ///</summary>
        [Display(Name = "地理位置-海拔高度", Order = 4)]
        public virtual decimal GeoLocation_Altitude { get; set; }


        ///<summary>
        /// 节点编号
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "节点编号", Order = 5)]
        public virtual string NodeID { get; set; }


        ///<summary>
        /// 最后短信
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "最后短信", Order = 6)]
        public virtual string SMS { get; set; }


        ///<summary>
        /// 温度
        ///</summary>
        [Display(Name = "温度", Order = 7)]
        public virtual decimal Temperature { get; set; }


        ///<summary>
        /// 湿度
        ///</summary>
        [Display(Name = "湿度", Order = 8)]
        public virtual decimal Humidity { get; set; }


        ///<summary>
        /// 市电电源
        ///</summary>
        [Display(Name = "市电电源", Order = 9)]
        public virtual bool ExternalPower { get; set; }


        ///<summary>
        /// 继电器1
        ///</summary>
        [Display(Name = "继电器1", Order = 10)]
        public virtual bool Relay1 { get; set; }


        ///<summary>
        /// 继电器2
        ///</summary>
        [Display(Name = "继电器2", Order = 11)]
        public virtual bool Relay2 { get; set; }


        ///<summary>
        /// 继电器3
        ///</summary>
        [Display(Name = "继电器3", Order = 12)]
        public virtual bool Relay3 { get; set; }


        ///<summary>
        /// 继电器4
        ///</summary>
        [Display(Name = "继电器4", Order = 13)]
        public virtual bool Relay4 { get; set; }


        ///<summary>
        /// 继电器5
        ///</summary>
        [Display(Name = "继电器5", Order = 14)]
        public virtual bool Relay5 { get; set; }


        ///<summary>
        /// 继电器6
        ///</summary>
        [Display(Name = "继电器6", Order = 15)]
        public virtual bool Relay6 { get; set; }


        ///<summary>
        /// 继电器7
        ///</summary>
        [Display(Name = "继电器7", Order = 16)]
        public virtual bool Relay7 { get; set; }


        ///<summary>
        /// 继电器8
        ///</summary>
        [Display(Name = "继电器8", Order = 17)]
        public virtual bool Relay8 { get; set; }


        ///<summary>
        /// 数值2
        ///</summary>
        [Display(Name = "数值2", Order = 18)]
        public virtual decimal Value2 { get; set; }


        ///<summary>
        /// 数值3
        ///</summary>
        [Display(Name = "数值3", Order = 19)]
        public virtual decimal Value3 { get; set; }


        ///<summary>
        /// 数值4
        ///</summary>
        [Display(Name = "数值4", Order = 20)]
        public virtual decimal Value4 { get; set; }


        ///<summary>
        /// 数值5
        ///</summary>
        [Display(Name = "数值5", Order = 21)]
        public virtual decimal Value5 { get; set; }


        ///<summary>
        /// 数值6
        ///</summary>
        [Display(Name = "数值6", Order = 22)]
        public virtual decimal Value6 { get; set; }


        ///<summary>
        /// 数值7
        ///</summary>
        [Display(Name = "数值7", Order = 23)]
        public virtual decimal Value7 { get; set; }


        ///<summary>
        /// 数值8
        ///</summary>
        [Display(Name = "数值8", Order = 24)]
        public virtual decimal Value8 { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 25)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 26)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}