//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.ZJC.Dtos
{

    /// <summary>
    /// 干湿沉降实时数据 Dto
    /// </summary>
    //[AutoMapFrom(typeof(ZjcRunStatus))]
public partial class ZjcRunStatusDto : EntityDto<Guid>
    {
        #region 构造方法
        public ZjcRunStatusDto()
        {
        }
        #endregion


        #region 基本属性

        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 1)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 干沉降总条数
        ///</summary>
        [Display(Name = "干沉降总条数", Order = 2)]
        public virtual ushort DryDepositionCount { get; set; }


        ///<summary>
        /// 当前仪器状态
        ///</summary>
        [Display(Name = "当前仪器状态", Order = 3)]
        public virtual ushort Status { get; set; }


        ///<summary>
        /// 设备实时时钟
        ///</summary>
        [Display(Name = "设备实时时钟", Order = 4)]
        public virtual DateTime InstrumentTime { get; set; }


        ///<summary>
        /// 前一天降雨总量
        ///</summary>
        [Display(Name = "前一天降雨总量", Order = 5)]
        public virtual decimal RainfallYesterday { get; set; }


        ///<summary>
        /// 当前逢雨雨量
        ///</summary>
        [Display(Name = "当前逢雨雨量", Order = 6)]
        public virtual decimal RainfallCurrent { get; set; }


        ///<summary>
        /// 环境温度
        ///</summary>
        [Display(Name = "环境温度", Order = 7)]
        public virtual decimal Temperature { get; set; }


        ///<summary>
        /// 湿度
        ///</summary>
        [Display(Name = "湿度", Order = 8)]
        public virtual decimal Humidity { get; set; }


        ///<summary>
        /// 机箱温度
        ///</summary>
        [Display(Name = "机箱温度", Order = 9)]
        public virtual decimal TempOfBox { get; set; }


        ///<summary>
        /// 采样桶温度
        ///</summary>
        [Display(Name = "采样桶温度", Order = 10)]
        public virtual decimal TempOfBucket { get; set; }


        ///<summary>
        /// 雨感器温度
        ///</summary>
        [Display(Name = "雨感器温度", Order = 11)]
        public virtual decimal TempOfRainSensor { get; set; }


        ///<summary>
        /// 查询日期内降雨总时间
        ///</summary>
        [Display(Name = "查询日期内降雨总时间", Order = 12)]
        public virtual ushort Raintimes { get; set; }


        ///<summary>
        /// 集雨桶水满
        ///</summary>
        [Display(Name = "集雨桶水满", Order = 13)]
        public virtual bool FilledWater { get; set; }


        ///<summary>
        /// 开盖超限
        ///</summary>
        [Display(Name = "开盖超限", Order = 14)]
        public virtual bool AlarmLidOpenedOver { get; set; }


        ///<summary>
        /// 关盖超限
        ///</summary>
        [Display(Name = "关盖超限", Order = 15)]
        public virtual bool AlarmLidClosedOver { get; set; }


        ///<summary>
        /// 机箱温控故障
        ///</summary>
        [Display(Name = "机箱温控故障", Order = 16)]
        public virtual bool AlarmBoxTemp { get; set; }


        ///<summary>
        /// 采样桶温控故障
        ///</summary>
        [Display(Name = "采样桶温控故障", Order = 17)]
        public virtual bool AlarmBucketTemp { get; set; }


        ///<summary>
        /// 感雨器温控故障
        ///</summary>
        [Display(Name = "感雨器温控故障", Order = 18)]
        public virtual bool AlarmRainSensor { get; set; }


        ///<summary>
        /// 干沉降桶液位满故障
        ///</summary>
        [Display(Name = "干沉降桶液位满故障", Order = 19)]
        public virtual bool AlarmDryBucketFilled { get; set; }


        ///<summary>
        /// 干沉降桶液位低故障
        ///</summary>
        [Display(Name = "干沉降桶液位低故障", Order = 20)]
        public virtual bool AlarmDryBucketWaterLess { get; set; }


        ///<summary>
        /// 集雨器水满故障
        ///</summary>
        [Display(Name = "集雨器水满故障", Order = 21)]
        public virtual bool AlarmJyqFilled { get; set; }


        ///<summary>
        /// 环境温度故障
        ///</summary>
        [Display(Name = "环境温度故障", Order = 22)]
        public virtual bool AlarmTemperature { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 23)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 状态更新时间
        ///</summary>
        [Display(Name = "状态更新时间", Order = 24)]
        public virtual DateTime? RunUpdateTime { get; set; }


        ///<summary>
        /// 警报更新时间
        ///</summary>
        [Display(Name = "警报更新时间", Order = 25)]
        public virtual DateTime? AlarmUpdateTime { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 26)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion



    }
}