//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Volo.Abp.Application.Dtos;

using HengDa.LiZongMing.REAMS;
namespace HengDa.LiZongMing.REAMS.DLL.Dtos
{

    /// <summary>
    /// DLL检测记录 ListDto
    /// </summary>
    //[AutoMapFrom(typeof(DllRecord))]
public partial class DllRecordListDto : EntityDto<Guid>
    {
        #region 构造方法
        public DllRecordListDto()
        {
        }
        #endregion


        #region 基本属性

        // ///<summary>
        // /// Id
        // ///</summary>
        // [Display(Name = "Id", Order = 25)]
        // public virtual Guid Id { get; set; }


        ///<summary>
        /// 命令动作
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "命令动作", Order = 26)]
        public virtual string Act { get; set; }


        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 27)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 记录时间
        ///</summary>
        [Display(Name = "记录时间", Order = 28)]
        public virtual long RecordTime { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 29)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 采样模批号
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "采样模批号", Order = 30)]
        public virtual string BatchNumber { get; set; }


        ///<summary>
        /// 是否空白值
        ///</summary>
        [Display(Name = "是否空白值", Order = 31)]
        public virtual bool IsEmpty { get; set; }


        ///<summary>
        /// alpha
        ///</summary>
        [Display(Name = "alpha", Order = 32)]
        public virtual decimal alpha { get; set; }


        ///<summary>
        /// beta0
        ///</summary>
        [Display(Name = "beta0", Order = 33)]
        public virtual decimal beta0 { get; set; }


        ///<summary>
        /// beta2
        ///</summary>
        [Display(Name = "beta2", Order = 34)]
        public virtual decimal beta2 { get; set; }


        ///<summary>
        /// beta
        ///</summary>
        [Display(Name = "beta", Order = 35)]
        public virtual decimal beta { get; set; }


        ///<summary>
        /// β/α比率
        ///</summary>
        [Display(Name = "β/α比率", Order = 36)]
        public virtual decimal ratio { get; set; }


        ///<summary>
        /// 原始数据
        ///</summary>
        [MaxLength(2000)]
        [Display(Name = "原始数据", Order = 37)]
        public virtual string rawData { get; set; }


        ///<summary>
        /// 空气质量指数
        ///</summary>
        [Display(Name = "空气质量指数", Order = 38)]
        public virtual decimal AQI { get; set; }


        ///<summary>
        /// 氟化物浓度
        ///</summary>
        [Display(Name = "氟化物浓度", Order = 39)]
        public virtual decimal Fluoride { get; set; }


        ///<summary>
        /// 污染物1
        ///</summary>
        [Display(Name = "污染物1", Order = 40)]
        public virtual decimal Item1 { get; set; }


        ///<summary>
        /// 污染物2
        ///</summary>
        [Display(Name = "污染物2", Order = 41)]
        public virtual decimal Item2 { get; set; }


        ///<summary>
        /// 温度
        ///</summary>
        [Display(Name = "温度", Order = 42)]
        public virtual decimal Temperature { get; set; }


        ///<summary>
        /// 湿度
        ///</summary>
        [Display(Name = "湿度", Order = 43)]
        public virtual decimal Humidity { get; set; }


        ///<summary>
        /// 气压
        ///</summary>
        [Display(Name = "气压", Order = 44)]
        public virtual decimal Atmosphere { get; set; }


        ///<summary>
        /// 风速 
        ///</summary>
        [Display(Name = "风速 ", Order = 45)]
        public virtual decimal WindSpeed { get; set; }


        ///<summary>
        /// 风向
        ///</summary>
        [Display(Name = "风向", Order = 46)]
        public virtual int WindDirection { get; set; }


        ///<summary>
        /// 雨量
        ///</summary>
        [Display(Name = "雨量", Order = 47)]
        public virtual decimal WaterRequire { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 48)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}