//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;


namespace HengDa.LiZongMing.REAMS.Devices
{

    /// <summary>
    /// 设备报警记录
    /// </summary>

    [Table(REAMSDbProperties.DbTablePrefix + "IotDeviceAlarm")]
    public partial class IotDeviceAlarm : Entity<Guid>, IHasCreationTime, IMultiTenant  // Entity<Guid> , IHasCreationTime, IHasModificationTime, IExtendableObject, IMustHaveTenant, IContent, IReadPiont, ISeo
    {
        #region 构造方法
        public IotDeviceAlarm()
        {
        }
        #endregion


        #region 构造方法Guid
        public IotDeviceAlarm(Guid id) : base(id)
        {
        }
        #endregion


        #region 基本属性

        // ///<summary>
        // /// 编号
        // ///</summary>
        // [Key]
        // [Column(Order = 1)]
        // [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        // [Required()]
        // [Display(Name = "编号", Order = 1)]
        // [UIHint("NotEdit")]
        // public override Guid Id { get; set; }

        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 2)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 类别
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "类别", Order = 3)]
        public virtual string LogType { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 4)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 级别
        ///</summary>
        [Display(Name = "级别", Order = 5)]
        public virtual int Level { get; set; }


        ///<summary>
        /// 消息
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "消息", Order = 6)]
        public virtual string Text { get; set; }


        ///<summary>
        /// 属性或部件
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "属性或部件", Order = 7)]
        public virtual string Prop { get; set; }


        ///<summary>
        /// 参数
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "参数", Order = 8)]
        public virtual string Data { get; set; }


        ///<summary>
        /// 通知
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "通知", Order = 9)]
        public virtual string Notify { get; set; }


        ///<summary>
        /// 恢复或处理结果
        ///</summary>
        [MaxLength(256)]
        [Display(Name = "恢复或处理结果", Order = 10)]
        public virtual string Restore { get; set; }


        ///<summary>
        /// 恢复或处理时间
        ///</summary>
        [Display(Name = "恢复或处理时间", Order = 11)]
        public virtual DateTime? UpdateTime { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 12)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}