//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;


namespace HengDa.LiZongMing.REAMS.ZJC
{

    /// <summary>
    /// 干沉降记录
    /// </summary>

    [Table(REAMSDbProperties.DbTablePrefix + "ZjcRecord")]
    public partial class ZjcRecord : Entity<Guid>, IHasCreationTime, IMultiTenant  // Entity<Guid> , IHasCreationTime, IHasModificationTime, IExtendableObject, IMustHaveTenant, IContent, IReadPiont, ISeo
    {
        #region 构造方法
        public ZjcRecord()
        {
        }
        #endregion


        #region 构造方法Guid
        public ZjcRecord(Guid id) : base(id)
        {
        }
        #endregion


        #region 基本属性

        ///<summary>
        /// 设备Id
        ///</summary>
        [Display(Name = "设备Id", Order = 1)]
        public virtual long DeviceId { get; set; }


        ///<summary>
        /// 干沉降起始日期
        ///</summary>
        [Display(Name = "干沉降起始日期", Order = 2)]
        public virtual DateTime StartTime { get; set; }


        ///<summary>
        /// 干沉降结束日期
        ///</summary>
        [Display(Name = "干沉降结束日期", Order = 3)]
        public virtual DateTime EndTime { get; set; }


        ///<summary>
        /// 创建时间
        ///</summary>
        [Display(Name = "创建时间", Order = 4)]
        public virtual DateTime CreationTime { get; set; }


        ///<summary>
        /// 多租户
        ///</summary>
        [Display(Name = "多租户", Order = 5)]
        public virtual Guid? TenantId { get; set; }


        #endregion

        #region 保留  手动添加属性

        #endregion


    }
}