//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using HengDa.LiZongMing.REAMS.NaI;
using Volo.Abp.Data;

namespace HengDa.LiZongMing.REAMS.Template
{

    /// <summary>
    /// AppTemplate
    /// </summary>

     public partial class AppTemplate : AggregateRoot<Guid>, IMultiTenant  // Entity<Guid> , IHasCreationTime, IHasModificationTime, IExtendableObject, IMustHaveTenant, IContent, IReadPiont, ISeo
      //public partial class AppTemplate : NaiRecord, IHasExtraProperties

    {
        #region 构造方法
        public AppTemplate()
        {
        }
        #endregion


        #region 构造方法Guid
        public AppTemplate(Guid id) : base(id)
        {
        }
        #endregion


        #region 基本属性

        ///<summary>
        /// 模板1
        ///</summary>
        [Display(Name = "模板1", Order = 0)]
        public virtual Guid? AddSegment { get; set; }

        ///<summary>
        /// 模板1
        ///</summary>
        [Display(Name = "模板2", Order = 1)]
        public virtual bool IsAddSegment { get; set; }
        public string Name { get; private set; }
        public Guid? TenantId { get; set; }
        #endregion

        #region 保留  手动添加属性

        #endregion

    }
}