//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.Crm;
using HengDa.LiZongMing.REAMS.Crm.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.Crm
{

    /// <summary>
    /// 工程师信息 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.CustomerService.Default*/)]
    public partial class CustomerServiceAppService : REAMSAppServiceBase<CustomerService, CustomerServiceDto, Guid, CustomerServicePagedRequest, CustomerServiceDto, CustomerServiceDto>, ICustomerServiceAppService
    {

        #region 构造方法

        //private readonly CustomerServiceManager _customerServiceManager;

        public CustomerServiceAppService(
            ICustomerServiceRepository repository  //mongodb必须用这个             IRepository<CustomerService, Guid> repository
            //CustomerServiceManager customerServiceManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.CustomerService.Query;
            //GetListPolicyName = REAMSPermissions.CustomerService.Query;
            //CreatePolicyName = REAMSPermissions.CustomerService.Create;
            //UpdatePolicyName = REAMSPermissions.CustomerService.Edit;
            //DeletePolicyName = REAMSPermissions.CustomerService.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.CustomerService.Query)]
        public override Task<CustomerServiceDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.CustomerService.Query)]
        public override Task<PagedResultDto<CustomerServiceDto>> GetListAsync(CustomerServicePagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.CustomerService.Create)]
        public async Task<CustomerServiceDto> GetOrNew(Nullable<Guid> id)
        {
            CustomerServiceDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new CustomerServiceDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.CustomerService.Create)]
        public override async Task<CustomerServiceDto> CreateAsync(CustomerServiceDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var customerService = MapToEntity(input);
            //return MapToGetOutputDto(customerService);
        }

        [Authorize(REAMSPermissions.CustomerService.Edit)]
        public override async Task<CustomerServiceDto> UpdateAsync(Guid id, CustomerServiceDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var customerService = await _customerServiceManager.GetCustomerServiceByIdAsync(input.Id);
            //MapToEntity(input, customerService);
            //CheckErrors(await _customerServiceManager.UpdateAsync(customerService));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _customerServiceManager.SetRoles(customerService, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.CustomerService.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var customerService = await _customerServiceManager.GetCustomerServiceByIdAsync(id);
            //await _customerServiceManager.DeleteAsync(customerService);
        }

        protected override async Task<CustomerService> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var customerService = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (customerService == null)
            //{
            //    throw new EntityNotFoundException(typeof(CustomerService), id);
            //}
            //return customerService;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="CustomerService"/> 时转换为 <see cref="CustomerServiceDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual CustomerServiceDto MapToGetOutputDto(CustomerService entity)
        {
            //return ObjectMapper.Map<CustomerService, CustomerServiceDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="CustomerService"/> 时转换为 <see cref="CustomerServiceDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<CustomerServiceDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override CustomerService MapToEntity(CustomerServiceDto createInput)
        {
            return base.MapToEntity(createInput);
            //var customerService = ObjectMapper.Map<CustomerService>(createInput);
            //customerService.SetNormalizedNames();
            //return customerService;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(CustomerServiceDto updateInput, CustomerService customerService)
        {
            base.MapToEntity(updateInput, customerService);
            //ObjectMapper.Map(updateInput, customerService);
            //customerService.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<CustomerService>> CreateFilteredQueryAsync(CustomerServicePagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Name.Contains(input.Keyword)
                        || x.Contact.Contains(input.Keyword)
                        || x.Mobile.Contains(input.Keyword)
                        || x.Email.Contains(input.Keyword)
                        || x.Address.Contains(input.Keyword)
                        || x.Remark.Contains(input.Keyword)
                        )
                 .WhereIf(!input.Name.IsNullOrWhiteSpace(), x => x.Name.Contains(input.Name))
                 .WhereIf(input.IsEnable.HasValue, x => x.IsEnable == input.IsEnable)
                 .WhereIf(!input.Mobile.IsNullOrWhiteSpace(), x => x.Mobile.Contains(input.Mobile))
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<CustomerService> ApplySorting(IQueryable<CustomerService> query, CustomerServicePagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}