//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成 by 明教主加强的代码生成模板( 作者 m8989@qq.com) 。
//     T4模板 + 阿明加强的代码生成模板
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果重新生成代码，这些更改将会丢失。
//      所以如有修改的必要，建议建立 partial 类进行增加自己的代码
//                              或使用 #region 保留  功能说明  和 #endregion 来包围
// </auto-generated>
//------------------------------------------------------------------------------

using HengDa.LiZongMing.REAMS;
using HengDa.LiZongMing.REAMS.Authorization;
using HengDa.LiZongMing.REAMS.Crm;
using HengDa.LiZongMing.REAMS.Crm.Dtos;

using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Domain.Repositories;



namespace HengDa.LiZongMing.REAMS.Crm
{

    /// <summary>
    /// 客户信息 EditDto
    /// </summary>

    [Authorize(/*REAMSPermissions.Customer.Default*/)]
    public partial class CustomerAppService : REAMSAppServiceBase<Customer, CustomerDto, Guid, CustomerPagedRequest, CustomerDto, CustomerDto>, ICustomerAppService
    {

        #region 构造方法

        //private readonly CustomerManager _customerManager;

        public CustomerAppService(
            ICustomerRepository repository  //mongodb必须用这个             IRepository<Customer, Guid> repository
            //CustomerManager customerManager
            ):base(repository)
        {

            //权限控制
            //GetPolicyName = REAMSPermissions.Customer.Query;
            //GetListPolicyName = REAMSPermissions.Customer.Query;
            //CreatePolicyName = REAMSPermissions.Customer.Create;
            //UpdatePolicyName = REAMSPermissions.Customer.Edit;
            //DeletePolicyName = REAMSPermissions.Customer.Delete;

        }

        #endregion


        [Authorize(REAMSPermissions.Customer.Query)]
        public override Task<CustomerDto> GetAsync(Guid id)
        {
            return base.GetAsync(id);
        }
        [Authorize(REAMSPermissions.Customer.Query)]
        public override Task<PagedResultDto<CustomerDto>> GetListAsync(CustomerPagedRequest input)
        {
            return base.GetListAsync(input);
        }
        /// <summary>
        /// 获取一个现有实体，或者新的默认实体
        /// </summary>
        [Authorize(REAMSPermissions.Customer.Create)]
        public async Task<CustomerDto> GetOrNew(Nullable<Guid> id)
        {
            CustomerDto editDto = null;

			if (id.HasValue)
			{
				var entity = await Repository.GetAsync(id.Value);
				editDto = MapToGetOutputDto(entity);
			}
			else
			{
				editDto = new CustomerDto();
			}

			return editDto;
        }

        [Authorize(REAMSPermissions.Customer.Create)]
        public override async Task<CustomerDto> CreateAsync(CustomerDto input)
        {
            //CheckCreatePermission();
            return await base.CreateAsync(input);
            //var customer = MapToEntity(input);
            //return MapToGetOutputDto(customer);
        }

        [Authorize(REAMSPermissions.Customer.Edit)]
        public override async Task<CustomerDto> UpdateAsync(Guid id, CustomerDto input)
        {
            //CheckUpdatePermission();
            return await base.UpdateAsync(id,input);

            //var customer = await _customerManager.GetCustomerByIdAsync(input.Id);
            //MapToEntity(input, customer);
            //CheckErrors(await _customerManager.UpdateAsync(customer));
            //if (input.RoleNames != null)
            //{
            //    CheckErrors(await _customerManager.SetRoles(customer, input.RoleNames));
            //}
            //return await Get(input);
        }

        [Authorize(REAMSPermissions.Customer.Delete)]
        public override  Task DeleteAsync(Guid id)
        {
            return base.DeleteAsync(id);
            //var customer = await _customerManager.GetCustomerByIdAsync(id);
            //await _customerManager.DeleteAsync(customer);
        }

        protected override async Task<Customer> GetEntityByIdAsync(Guid id)
        {
            return await base.GetEntityByIdAsync(id);
            //var customer = await Repository.GetAllIncluding(x => x.Roles).FirstOrDefaultAsync(x => x.Id == id);
            //if (customer == null)
            //{
            //    throw new EntityNotFoundException(typeof(Customer), id);
            //}
            //return customer;
            //return await Repository.GetAsync(id);
        }

        #region   IObjectMapper实体转换方法
        /*
        /// <summary>
        /// 读取单个实体 <see cref="Customer"/> 时转换为 <see cref="CustomerDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual CustomerDto MapToGetOutputDto(Customer entity)
        {
            //return ObjectMapper.Map<Customer, CustomerDto>(entity);
            //return base.MapToGetOutputDto(entity);
        }

        /// <summary>
        /// 读取列表实体 <see cref="Customer"/> 时转换为 <see cref="CustomerDto"/>.
        /// It uses <see cref="IObjectMapper"/> by default.
        /// </summary>
        protected virtual PagedResultDto<CustomerDto> MapToGetListOutputDto(TEntity entity)
        {
            //return ObjectMapper.Map<TEntity, TGetListOutputDto>(entity);
            //return base.MapToGetListOutputDto(entity);
        }

        /// <summary>
        /// 新增时将参数转换成实体
        /// </summary>
        protected override Customer MapToEntity(CustomerDto createInput)
        {
            return base.MapToEntity(createInput);
            //var customer = ObjectMapper.Map<Customer>(createInput);
            //customer.SetNormalizedNames();
            //return customer;
        }

        /// <summary>
        /// 编辑时将参数转换成实体
        /// </summary>
        protected override void MapToEntity(CustomerDto updateInput, Customer customer)
        {
            base.MapToEntity(updateInput, customer);
            //ObjectMapper.Map(updateInput, customer);
            //customer.SetNormalizedNames();
        }
        */
        #endregion

        #region   不保留  条件过滤
        protected override Task<IQueryable<Customer>> CreateFilteredQueryAsync(CustomerPagedRequest input)
        {
            var q = Repository
                //.AsNoTracking()
                //.WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Title.Contains(input.Keyword) )

                 .WhereIf(!input.Keyword.IsNullOrWhiteSpace(), x => x.Name.Contains(input.Keyword)
                        || x.Sales.Contains(input.Keyword)
                        || x.Company.Contains(input.Keyword)
                        || x.Mobile.Contains(input.Keyword)
                        || x.Email.Contains(input.Keyword)
                        || x.Address.Contains(input.Keyword)
                        || x.Remark.Contains(input.Keyword)
                        )
                 .WhereIf(!input.Name.IsNullOrWhiteSpace(), x => x.Name.Contains(input.Name))
                 .WhereIf(input.IsEnable.HasValue, x => x.IsEnable == input.IsEnable)
                 .WhereIf(!input.Mobile.IsNullOrWhiteSpace(), x => x.Mobile.Contains(input.Mobile))
                 .WhereIf(input.TenantId.HasValue, x => x.TenantId == input.TenantId)
                ;
            return Task.FromResult(q);
        }
        #endregion

        #region   不保留 排序
        protected override IQueryable<Customer> ApplySorting(IQueryable<Customer> query, CustomerPagedRequest input)
        {
            return base.ApplySorting(query, input);
            //return query.OrderByDescending(r => r.Id);
        }
        #endregion

        #region 不保留  手动添加

        #endregion


    }
}